# Generated by Django 5.2.15 on 2026-06-23 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=191, unique=True, verbose_name='事件幂等键')),
                ('source_module', models.CharField(max_length=80, verbose_name='来源模块')),
                ('event_type', models.CharField(max_length=120, verbose_name='事件类型')),
                ('event_category', models.CharField(max_length=80, verbose_name='事件分类')),
                ('severity', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('high', '高风险'), ('critical', '严重')], max_length=20, verbose_name='严重级别')),
                ('title_zh', models.CharField(max_length=200, verbose_name='中文标题')),
                ('message_zh', models.TextField(verbose_name='中文摘要')),
                ('business_status', models.CharField(blank=True, max_length=80, verbose_name='业务状态')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('related_object_type', models.CharField(blank=True, max_length=120, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, max_length=120, verbose_name='关联对象 ID')),
                ('related_object_label', models.CharField(blank=True, max_length=200, verbose_name='关联对象标签')),
                ('correlation_key', models.CharField(blank=True, max_length=255, verbose_name='关联键')),
                ('dedupe_key', models.CharField(blank=True, max_length=255, verbose_name='去重键')),
                ('cooldown_key', models.CharField(blank=True, max_length=255, verbose_name='冷却键')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('event_time_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='事件 UTC 时间')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='脱敏载荷摘要')),
                ('evidence_refs', models.JSONField(blank=True, default=list, verbose_name='证据引用')),
                ('is_dry_run', models.BooleanField(default=False, verbose_name='是否 dry-run')),
                ('delivery_enabled', models.BooleanField(default=False, verbose_name='是否允许外部投递')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'indexes': [models.Index(fields=['source_module', 'event_type'], name='alerts_aler_source__8f25ba_idx'), models.Index(fields=['severity', 'created_at_utc'], name='alerts_aler_severit_e3f0c5_idx'), models.Index(fields=['trace_id'], name='alerts_aler_trace_i_7d033e_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='alerts_aler_related_5cc75c_idx')],
            },
        ),
    ]
