# Generated by Django 5.2.15 on 2026-06-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=120, verbose_name='路由代码')),
                ('route_version', models.CharField(default='1.0', max_length=40, verbose_name='路由版本')),
                ('source_module', models.CharField(blank=True, max_length=80, verbose_name='来源模块')),
                ('event_category', models.CharField(blank=True, max_length=80, verbose_name='事件分类')),
                ('event_type', models.CharField(blank=True, max_length=120, verbose_name='事件类型')),
                ('min_severity', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('high', '高风险'), ('critical', '严重')], default='info', max_length=20, verbose_name='最低严重级别')),
                ('channel', models.CharField(default='hermes', max_length=80, verbose_name='通知渠道')),
                ('template_code', models.CharField(blank=True, max_length=120, verbose_name='模板代码')),
                ('template_version', models.CharField(blank=True, max_length=40, verbose_name='模板版本')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('cooldown_seconds', models.PositiveIntegerField(default=0, verbose_name='冷却秒数')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='最大投递次数')),
                ('retry_policy', models.JSONField(blank=True, default=dict, verbose_name='重试策略')),
                ('route_hash', models.CharField(blank=True, max_length=80, verbose_name='路由指纹')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'event_category', 'event_type'], name='alerts_noti_enabled_f9fb6d_idx'), models.Index(fields=['source_module', 'enabled'], name='alerts_noti_source__0267e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('route_code', 'route_version'), name='uniq_notification_route_version')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=120, verbose_name='模板代码')),
                ('template_version', models.CharField(default='1.0', max_length=40, verbose_name='模板版本')),
                ('channel', models.CharField(default='hermes', max_length=80, verbose_name='通知渠道')),
                ('language', models.CharField(default='zh', max_length=20, verbose_name='语言')),
                ('title_template', models.CharField(max_length=300, verbose_name='标题模板')),
                ('body_template', models.TextField(verbose_name='正文模板')),
                ('max_length', models.PositiveIntegerField(default=4000, verbose_name='最大长度')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('template_hash', models.CharField(blank=True, max_length=80, verbose_name='模板指纹')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'channel'], name='alerts_noti_enabled_cdc0ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('template_code', 'template_version'), name='uniq_notification_template_version')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_attempt_key', models.CharField(max_length=191, unique=True, verbose_name='投递尝试幂等键')),
                ('channel', models.CharField(max_length=80, verbose_name='通知渠道')),
                ('route_code', models.CharField(blank=True, max_length=120, verbose_name='路由代码')),
                ('template_code', models.CharField(blank=True, max_length=120, verbose_name='模板代码')),
                ('template_version', models.CharField(blank=True, max_length=40, verbose_name='模板版本')),
                ('route_config_hash', models.CharField(blank=True, max_length=80, verbose_name='路由配置指纹')),
                ('template_hash', models.CharField(blank=True, max_length=80, verbose_name='模板指纹')),
                ('delivery_status', models.CharField(choices=[('pending', '待投递'), ('sending', '投递中'), ('sent', '已投递'), ('failed', '投递失败'), ('suppressed', '已抑制'), ('abandoned', '已放弃')], default='pending', max_length=40, verbose_name='投递状态')),
                ('attempt_sequence', models.PositiveIntegerField(default=1, verbose_name='尝试序号')),
                ('provider_idempotency_key', models.CharField(blank=True, max_length=191, verbose_name='供应商幂等键')),
                ('provider_message_id', models.CharField(blank=True, max_length=191, verbose_name='供应商消息 ID')),
                ('request_sent', models.BooleanField(default=False, verbose_name='是否已发出请求')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('provider_error_code', models.CharField(blank=True, max_length=120, verbose_name='供应商错误码')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误说明')),
                ('retryable', models.BooleanField(default=False, verbose_name='是否可重试')),
                ('next_retry_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='下次重试 UTC 时间')),
                ('claimed_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='领取 UTC 时间')),
                ('started_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='结束 UTC 时间')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('sanitized_request_summary', models.JSONField(blank=True, default=dict, verbose_name='脱敏请求摘要')),
                ('sanitized_response_summary', models.JSONField(blank=True, default=dict, verbose_name='脱敏响应摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('alert_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='alerts.alertevent')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery_status', 'created_at_utc'], name='alerts_noti_deliver_fbf4d4_idx'), models.Index(fields=['alert_event', 'delivery_status'], name='alerts_noti_alert_e_d55ec8_idx'), models.Index(fields=['trace_id'], name='alerts_noti_trace_i_d0be16_idx')],
                'constraints': [models.UniqueConstraint(fields=('alert_event', 'route_code', 'channel', 'attempt_sequence'), name='uniq_notification_attempt_sequence')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppression_type', models.CharField(max_length=80, verbose_name='抑制类型')),
                ('dedupe_key', models.CharField(blank=True, max_length=255, verbose_name='去重键')),
                ('cooldown_key', models.CharField(blank=True, max_length=255, verbose_name='冷却键')),
                ('window_start_utc', models.DateTimeField(blank=True, null=True, verbose_name='窗口开始 UTC 时间')),
                ('window_end_utc', models.DateTimeField(blank=True, null=True, verbose_name='窗口结束 UTC 时间')),
                ('reason_code', models.CharField(max_length=120, verbose_name='原因代码')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('alert_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='alerts.alertevent')),
            ],
            options={
                'indexes': [models.Index(fields=['alert_event', 'reason_code'], name='alerts_noti_alert_e_02f22a_idx'), models.Index(fields=['suppression_type', 'created_at_utc'], name='alerts_noti_suppres_f83efc_idx'), models.Index(fields=['trace_id'], name='alerts_noti_trace_i_60627b_idx')],
            },
        ),
    ]
