# Generated by Django 5.2.15 on 2026-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeGuardIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=191, unique=True, verbose_name='问题幂等键')),
                ('issue_type', models.CharField(max_length=120, verbose_name='问题类型')),
                ('severity', models.CharField(choices=[('info', '普通'), ('warning', '警告'), ('high', '高风险'), ('critical', '严重')], max_length=20, verbose_name='严重级别')),
                ('status', models.CharField(choices=[('open', '未解决'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('ignored', '已忽略')], default='open', max_length=40, verbose_name='问题状态')),
                ('first_seen_at_utc', models.DateTimeField(verbose_name='首次发现 UTC 时间')),
                ('last_seen_at_utc', models.DateTimeField(verbose_name='最近发现 UTC 时间')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='出现次数')),
                ('resolved_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='解决 UTC 时间')),
                ('related_object_type', models.CharField(blank=True, max_length=120, verbose_name='关联对象类型')),
                ('related_object_id', models.CharField(blank=True, max_length=120, verbose_name='关联对象 ID')),
                ('related_trace_id', models.CharField(blank=True, max_length=80, verbose_name='关联 trace_id')),
                ('description_zh', models.CharField(max_length=500, verbose_name='中文说明')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='证据摘要')),
                ('needs_manual_attention', models.BooleanField(default=True, verbose_name='是否需要人工关注')),
                ('alert_event_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='AlertEvent ID')),
                ('last_alerted_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='最近告警 UTC 时间')),
                ('acknowledged_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='确认 UTC 时间')),
                ('acknowledged_by', models.CharField(blank=True, max_length=120, verbose_name='确认人')),
                ('resolution_note', models.CharField(blank=True, max_length=500, verbose_name='解决说明')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'severity'], name='runtime_gua_status_e72ddd_idx'), models.Index(fields=['issue_type', 'status'], name='runtime_gua_issue_t_e69b84_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='runtime_gua_related_8cb3fd_idx'), models.Index(fields=['related_trace_id'], name='runtime_gua_related_b4f957_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuntimeGuardRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=191, unique=True, verbose_name='巡检运行幂等键')),
                ('status', models.CharField(choices=[('running', '运行中'), ('succeeded', '已完成'), ('partial_failed', '部分失败'), ('failed', '失败')], max_length=40, verbose_name='运行状态')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('started_at_utc', models.DateTimeField(verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='结束 UTC 时间')),
                ('checked_item_count', models.PositiveIntegerField(default=0, verbose_name='检查对象数量')),
                ('created_issue_count', models.PositiveIntegerField(default=0, verbose_name='新增问题数量')),
                ('updated_issue_count', models.PositiveIntegerField(default=0, verbose_name='更新问题数量')),
                ('alert_event_count', models.PositiveIntegerField(default=0, verbose_name='告警事件数量')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误数量')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'started_at_utc'], name='runtime_gua_status_9e05ec_idx'), models.Index(fields=['trace_id'], name='runtime_gua_trace_i_3743f3_idx')],
            },
        ),
    ]
