# Generated by Django 5.2.15 on 2026-06-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('binance_account_sync', '0001_initial'),
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationRunPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_utc', models.DateTimeField(verbose_name='周期开始 UTC')),
                ('period_end_utc', models.DateTimeField(verbose_name='周期结束 UTC')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('formula_version', models.CharField(default='p0_position_quantity_delta_v1', max_length=80, verbose_name='计算公式版本')),
                ('start_position_quantity', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期初持仓数量')),
                ('end_position_quantity', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期末持仓数量')),
                ('net_fill_quantity', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='周期内净成交数量')),
                ('cycle_floating_pnl', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='周期浮动表现')),
                ('cycle_floating_pnl_pct', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='周期浮动表现比例')),
                ('start_mark_price', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期初 mark price')),
                ('end_mark_price', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期末 mark price')),
                ('start_unrealized_pnl', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期初未实现盈亏')),
                ('end_unrealized_pnl', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期末未实现盈亏')),
                ('start_notional', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期初名义价值')),
                ('end_notional', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='期末名义价值')),
                ('has_decision_snapshot', models.BooleanField(default=False, verbose_name='是否有关联目标仓位决策')),
                ('has_order_plan', models.BooleanField(default=False, verbose_name='是否有关联订单计划')),
                ('has_candidate_order_intent', models.BooleanField(default=False, verbose_name='是否有关联候选订单意图')),
                ('has_risk_check', models.BooleanField(default=False, verbose_name='是否有关联风控结果')),
                ('has_approved_order_intent', models.BooleanField(default=False, verbose_name='是否有关联审批通过订单意图')),
                ('has_execution_preparation', models.BooleanField(default=False, verbose_name='是否有关联执行准备')),
                ('has_order_submission', models.BooleanField(default=False, verbose_name='是否有关联订单提交')),
                ('has_terminal_order_status', models.BooleanField(default=False, verbose_name='是否有关联终态订单状态')),
                ('has_fill', models.BooleanField(default=False, verbose_name='是否有关联成交事实')),
                ('order_submission_status', models.CharField(blank=True, max_length=40, verbose_name='订单提交状态')),
                ('terminal_exchange_order_status', models.CharField(blank=True, max_length=80, verbose_name='交易所终态订单状态')),
                ('order_realized_pnl', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='周期订单已实现盈亏')),
                ('order_commission', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='周期手续费')),
                ('order_net_realized_pnl', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='周期订单净已实现盈亏')),
                ('related_alert_count', models.PositiveIntegerField(default=0, verbose_name='关联告警数量')),
                ('related_runtime_guard_issue_count', models.PositiveIntegerField(default=0, verbose_name='关联巡检问题数量')),
                ('calculation_status', models.CharField(choices=[('calculated', '已计算'), ('insufficient_snapshot', '快照不足'), ('skipped', '已跳过'), ('failed', '计算失败')], default='calculated', max_length=40, verbose_name='计算状态')),
                ('reason_code', models.CharField(max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('input_refs_hash', models.CharField(max_length=80, verbose_name='输入事实指纹')),
                ('result_hash', models.CharField(max_length=80, verbose_name='结果指纹')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('operator_id', models.CharField(blank=True, max_length=120, verbose_name='操作人 ID')),
                ('calculated_at_utc', models.DateTimeField(verbose_name='计算 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('end_account_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_ends', to='binance_account_sync.binanceaccountsnapshot')),
                ('end_binance_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_ends', to='binance_account_sync.binancesyncrun')),
                ('end_orchestration_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_ends', to='orchestration.orchestrationrun')),
                ('end_position_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_ends', to='binance_account_sync.binancepositionsnapshot')),
                ('start_account_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_starts', to='binance_account_sync.binanceaccountsnapshot')),
                ('start_binance_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_starts', to='binance_account_sync.binancesyncrun')),
                ('start_orchestration_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_starts', to='orchestration.orchestrationrun')),
                ('start_position_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_period_starts', to='binance_account_sync.binancepositionsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['period_start_utc', 'period_end_utc'], name='performance_period__1e8a0a_idx'), models.Index(fields=['market_type', 'account_domain', 'symbol'], name='performance_market__28fdb6_idx'), models.Index(fields=['calculation_status', 'calculated_at_utc'], name='performance_calcula_592dd9_idx'), models.Index(fields=['trace_id'], name='performance_trace_i_dc7310_idx')],
                'constraints': [models.UniqueConstraint(fields=('start_orchestration_run', 'end_orchestration_run', 'market_type', 'account_domain', 'symbol'), name='uniq_orchestration_run_performance_period')],
            },
        ),
    ]
