# Generated by Django 5.2.15 on 2026-06-25 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution_preparation', '0002_alter_preparedorderintent_status'),
        ('order_plan', '0003_alter_orderplan_status'),
        ('risk_check', '0002_alter_approvedorderintent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_submission_attempt_key', models.CharField(max_length=191, unique=True, verbose_name='订单提交尝试幂等键')),
                ('business_request_key', models.CharField(max_length=191, verbose_name='业务幂等键')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('endpoint_family', models.CharField(blank=True, max_length=40, verbose_name='Gateway endpoint family')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('side', models.CharField(max_length=10, verbose_name='订单方向')),
                ('position_side', models.CharField(max_length=20, verbose_name='持仓方向')),
                ('position_mode', models.CharField(max_length=40, verbose_name='持仓模式')),
                ('order_type', models.CharField(max_length=40, verbose_name='订单类型')),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='冻结提交数量')),
                ('quantity_unit', models.CharField(max_length=40, verbose_name='数量单位')),
                ('reduce_only', models.BooleanField(verbose_name='reduceOnly')),
                ('order_notional', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='订单名义价值')),
                ('client_order_id', models.CharField(max_length=36, unique=True, verbose_name='Binance clientOrderId')),
                ('idempotency_key', models.CharField(max_length=191, unique=True, verbose_name='提交幂等键')),
                ('frozen_order_request', models.JSONField(default=dict, verbose_name='冻结订单请求')),
                ('request_payload_hash', models.CharField(max_length=80, verbose_name='请求载荷 hash')),
                ('status', models.CharField(choices=[('created', '已创建'), ('submitting', '提交中'), ('accepted', '交易所已接受提交请求'), ('rejected', '交易所明确拒绝'), ('unknown', '提交结果未知'), ('blocked_before_submit', '提交前阻断'), ('failed_before_submit', '提交前失败')], max_length=40, verbose_name='提交状态')),
                ('request_sent', models.BooleanField(default=False, verbose_name='请求是否已发出')),
                ('response_received', models.BooleanField(default=False, verbose_name='是否收到响应')),
                ('gateway_attempt_count', models.PositiveIntegerField(default=0, verbose_name='Gateway 技术尝试次数')),
                ('exchange_order_id', models.CharField(blank=True, max_length=120, verbose_name='交易所订单 ID')),
                ('exchange_client_order_id', models.CharField(blank=True, max_length=120, verbose_name='交易所 clientOrderId')),
                ('exchange_status', models.CharField(blank=True, max_length=80, verbose_name='交易所响应状态')),
                ('sanitized_exchange_response', models.JSONField(blank=True, default=dict, verbose_name='脱敏交易所响应')),
                ('exchange_response_hash', models.CharField(blank=True, max_length=80, verbose_name='交易所响应 hash')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('binance_error_code', models.CharField(blank=True, max_length=80, verbose_name='Binance 错误码')),
                ('sanitized_error_message', models.CharField(blank=True, max_length=500, verbose_name='脱敏错误摘要')),
                ('exception_class', models.CharField(blank=True, max_length=120, verbose_name='异常类型')),
                ('reason_code', models.CharField(max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('rate_limit_metadata', models.JSONField(blank=True, default=dict, verbose_name='限频元数据')),
                ('alert_event_ids', models.JSONField(blank=True, default=list, verbose_name='AlertEvent ID')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('claimed_at_utc', models.DateTimeField(verbose_name='抢占 UTC 时间')),
                ('submitted_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='提交调用 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='完成 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('active_lock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempts', to='order_plan.orderplanactivelock')),
                ('approved_order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempts', to='risk_check.approvedorderintent')),
                ('candidate_order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempts', to='order_plan.candidateorderintent')),
                ('execution_preparation_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempts', to='execution_preparation.executionpreparationresult')),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempts', to='order_plan.orderplan')),
                ('prepared_order_intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempt', to='execution_preparation.preparedorderintent')),
                ('risk_check_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_submission_attempts', to='risk_check.riskcheckresult')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at_utc'], name='execution_o_status_7bac9b_idx'), models.Index(fields=['market_type', 'account_domain', 'symbol'], name='execution_o_market__f50c2b_idx'), models.Index(fields=['order_plan'], name='execution_o_order_p_236e6c_idx'), models.Index(fields=['prepared_order_intent'], name='execution_o_prepare_1bd76d_idx'), models.Index(fields=['client_order_id'], name='execution_o_client__5253a9_idx'), models.Index(fields=['trace_id'], name='execution_o_trace_i_7a160e_idx')],
            },
        ),
    ]
