# Generated by Django 5.2.15 on 2026-06-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0001_initial'),
        ('execution_preparation', '0002_alter_preparedorderintent_status'),
        ('order_plan', '0003_alter_orderplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusSyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status_sync_key', models.CharField(max_length=191, unique=True, verbose_name='订单状态查询幂等键')),
                ('business_request_key', models.CharField(max_length=191, verbose_name='业务幂等键')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('endpoint_family', models.CharField(blank=True, max_length=40, verbose_name='Gateway endpoint family')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('query_identifier_type', models.CharField(max_length=40, verbose_name='查询编号类型')),
                ('client_order_id', models.CharField(blank=True, max_length=120, verbose_name='Binance clientOrderId')),
                ('exchange_order_id_requested', models.CharField(blank=True, max_length=120, verbose_name='请求使用的交易所订单 ID')),
                ('poll_mode', models.CharField(default='immediate', max_length=40, verbose_name='轮询模式')),
                ('poll_sequence', models.PositiveIntegerField(verbose_name='逻辑轮询序号')),
                ('polling_started_at_utc', models.DateTimeField(verbose_name='轮询开始 UTC 时间')),
                ('polling_deadline_utc', models.DateTimeField(verbose_name='轮询截止 UTC 时间')),
                ('scheduled_at_utc', models.DateTimeField(verbose_name='本轮计划 UTC 时间')),
                ('query_started_at_utc', models.DateTimeField(verbose_name='查询开始 UTC 时间')),
                ('query_finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='查询完成 UTC 时间')),
                ('query_outcome', models.CharField(choices=[('found', '查询到订单'), ('not_found', '交易所明确未找到订单'), ('unknown', '查询结果未知'), ('failed_before_query', '查询前失败'), ('blocked_before_query', '查询前阻断')], max_length=40, verbose_name='查询结果')),
                ('reason_code', models.CharField(max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('request_sent', models.BooleanField(default=False, verbose_name='请求是否已发出')),
                ('response_received', models.BooleanField(default=False, verbose_name='是否收到响应')),
                ('gateway_attempt_count', models.PositiveIntegerField(default=0, verbose_name='Gateway 技术尝试次数')),
                ('gateway_latency_ms', models.PositiveIntegerField(default=0, verbose_name='Gateway 延迟毫秒')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('binance_error_code', models.CharField(blank=True, max_length=80, verbose_name='Binance 错误码')),
                ('sanitized_error_message', models.CharField(blank=True, max_length=500, verbose_name='脱敏错误摘要')),
                ('exchange_order_id_returned', models.CharField(blank=True, max_length=120, verbose_name='返回的交易所订单 ID')),
                ('exchange_client_order_id_returned', models.CharField(blank=True, max_length=120, verbose_name='返回的 clientOrderId')),
                ('exchange_status', models.CharField(blank=True, max_length=80, verbose_name='交易所订单状态')),
                ('exchange_status_observed_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='状态观测 UTC 时间')),
                ('is_recognized_status', models.BooleanField(default=False, verbose_name='是否识别交易所状态')),
                ('is_terminal_status', models.BooleanField(default=False, verbose_name='是否明确终态')),
                ('terminal_policy_version', models.CharField(default='1.0', max_length=40, verbose_name='终态识别规则版本')),
                ('submission_resolution_status', models.CharField(choices=[('unresolved', '仍未确认'), ('order_found', '已确认订单存在'), ('terminal_confirmed', '已确认订单终态'), ('not_queryable', '不允许查询')], default='unresolved', max_length=40, verbose_name='提交结果解析状态')),
                ('sanitized_response', models.JSONField(blank=True, default=dict, verbose_name='脱敏交易所响应')),
                ('response_hash', models.CharField(blank=True, max_length=80, verbose_name='交易所响应 hash')),
                ('rate_limit_metadata', models.JSONField(blank=True, default=dict, verbose_name='限频元数据')),
                ('alert_event_ids', models.JSONField(blank=True, default=list, verbose_name='AlertEvent ID')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('active_lock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_sync_records', to='order_plan.orderplanactivelock')),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_sync_records', to='order_plan.orderplan')),
                ('order_submission_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_sync_records', to='execution.ordersubmissionattempt')),
                ('prepared_order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_status_sync_records', to='execution_preparation.preparedorderintent')),
            ],
            options={
                'indexes': [models.Index(fields=['order_submission_attempt', 'poll_mode', 'poll_sequence'], name='order_statu_order_s_e90b76_idx'), models.Index(fields=['query_outcome', 'created_at_utc'], name='order_statu_query_o_a83fb7_idx'), models.Index(fields=['is_terminal_status', 'created_at_utc'], name='order_statu_is_term_e7f64e_idx'), models.Index(fields=['market_type', 'account_domain', 'symbol'], name='order_statu_market__4d97f7_idx'), models.Index(fields=['trace_id'], name='order_statu_trace_i_f94c4d_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_submission_attempt', 'poll_mode', 'poll_sequence'), name='uniq_order_status_sync_attempt_mode_sequence')],
            },
        ),
    ]
