/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is kept explicit here
// because this repository does not use a scaffold command to create the frontend.
