# Generated by Django 5.2.15 on 2026-06-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeTradingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(default='default', max_length=80, unique=True, verbose_name='配置键')),
                ('runtime_real_trading_permission', models.BooleanField(default=False, verbose_name='MySQL 真实交易运行开关')),
                ('updated_by', models.CharField(blank=True, max_length=120, verbose_name='最后更新人')),
                ('updated_reason', models.CharField(blank=True, max_length=500, verbose_name='最后更新原因')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'verbose_name': '真实交易运行配置',
                'verbose_name_plural': '真实交易运行配置',
            },
        ),
    ]
