# Generated by Django 5.2.15 on 2026-06-23 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(max_length=120, verbose_name='特征代码')),
                ('definition_version', models.CharField(default='1.0.0', max_length=80, verbose_name='定义版本')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('value_type', models.CharField(choices=[('decimal', '数值'), ('boolean', '布尔'), ('text', '文本')], default='decimal', max_length=40, verbose_name='值类型')),
                ('input_timeframes', models.JSONField(blank=True, default=list, verbose_name='输入周期')),
                ('output_schema_version', models.CharField(default='1.0', max_length=80, verbose_name='输出 schema 版本')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否可被版本包选择')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['feature_code', 'definition_version'], name='strategy_an_feature_528aea_idx'), models.Index(fields=['algorithm_name', 'algorithm_version'], name='strategy_an_algorit_48e829_idx')],
                'constraints': [models.UniqueConstraint(fields=('feature_code', 'definition_version'), name='uniq_feature_definition_version')],
            },
        ),
        migrations.CreateModel(
            name='StrategyAnalysisRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_code', models.CharField(max_length=120, unique=True, verbose_name='版本包代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('release_hash', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='版本包指纹')),
                ('approval_status', models.CharField(choices=[('draft', '草稿'), ('validating', '待验证'), ('approved', '已批准'), ('rejected', '已拒绝'), ('invalidated', '已失效')], default='draft', max_length=40, verbose_name='批准状态')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='是否当前启用')),
                ('validation_evidence_count', models.PositiveIntegerField(default=0, verbose_name='验证证据数量')),
                ('approved_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='批准 UTC 时间')),
                ('activated_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='启用 UTC 时间')),
                ('deactivated_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='停用 UTC 时间')),
                ('created_by', models.CharField(blank=True, max_length=120, verbose_name='创建人')),
                ('approved_by', models.CharField(blank=True, max_length=120, verbose_name='批准人')),
                ('activated_by', models.CharField(blank=True, max_length=120, verbose_name='启用人')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['approval_status', 'is_active'], name='strategy_an_approva_ba1c53_idx'), models.Index(fields=['release_hash'], name='strategy_an_release_19969a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], default='created', max_length=40, verbose_name='状态')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('is_usable', models.BooleanField(default=True, verbose_name='是否可用')),
                ('allows_atomic_signal', models.BooleanField(default=True, verbose_name='允许原子信号消费')),
                ('definition_set_hash', models.CharField(max_length=80, verbose_name='特征定义集指纹')),
                ('feature_count', models.PositiveIntegerField(default=0, verbose_name='特征数量')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_sets', to='market_data.marketsnapshot')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_sets', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyAnalysisReleaseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('action', models.CharField(choices=[('approve', '批准'), ('reject', '拒绝'), ('invalidate', '失效'), ('activate', '启用'), ('deactivate', '停用'), ('rollback', '回滚')], max_length=40, verbose_name='动作')),
                ('operator_id', models.CharField(max_length=120, verbose_name='操作者')),
                ('reason', models.CharField(max_length=500, verbose_name='原因')),
                ('operated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作 UTC 时间')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('previous_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_activations', to='strategy_analysis.strategyanalysisrelease')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyAnalysisReleaseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('action', models.CharField(choices=[('approve', '批准'), ('reject', '拒绝'), ('invalidate', '失效'), ('activate', '启用'), ('deactivate', '停用'), ('rollback', '回滚')], max_length=40, verbose_name='动作')),
                ('validation_evidence_refs', models.JSONField(blank=True, default=list, verbose_name='验证证据引用')),
                ('reason', models.CharField(max_length=500, verbose_name='原因')),
                ('operator_id', models.CharField(max_length=120, verbose_name='操作者')),
                ('operated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作 UTC 时间')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyAnalysisReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('feature_definition', '特征定义'), ('atomic_signal_definition', '原子信号定义'), ('domain_signal_definition', '领域定义'), ('market_regime_definition', '市场环境定义'), ('strategy_route_policy', '策略路由策略'), ('strategy_route_rule', '策略路由规则'), ('strategy_definition', '策略定义'), ('strategy_signal_quality_rule_set', '策略信号质量规则集'), ('decision_policy_definition', '目标仓位决策定义')], max_length=80, verbose_name='组件类型')),
                ('component_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='组件对象 ID')),
                ('component_code', models.CharField(max_length=160, verbose_name='组件代码')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('algorithm_name', models.CharField(blank=True, max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(blank=True, max_length=80, verbose_name='算法版本')),
                ('params_hash', models.CharField(blank=True, max_length=80, verbose_name='参数指纹')),
                ('dependency_hash', models.CharField(blank=True, max_length=80, verbose_name='依赖指纹')),
                ('expected_definition_set_hash', models.CharField(blank=True, max_length=80, verbose_name='模块定义集指纹')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='冻结摘要')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyAnalysisReleaseValidationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('evidence_type', models.CharField(max_length=80, verbose_name='证据类型')),
                ('evidence_ref', models.CharField(max_length=255, verbose_name='证据引用')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('created_by', models.CharField(blank=True, max_length=120, verbose_name='创建人')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_evidence', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_code', models.CharField(max_length=120, verbose_name='特征代码')),
                ('feature_definition_hash', models.CharField(max_length=80, verbose_name='特征定义指纹')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('value_type', models.CharField(choices=[('decimal', '数值'), ('boolean', '布尔'), ('text', '文本')], max_length=40, verbose_name='值类型')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='数值')),
                ('bool_value', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('text_value', models.CharField(blank=True, max_length=255, verbose_name='文本值')),
                ('output_schema_version', models.CharField(max_length=80, verbose_name='输出 schema 版本')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='证据摘要')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], default='created', max_length=40, verbose_name='状态')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('feature_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='strategy_analysis.featuredefinition')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='strategy_analysis.featureset')),
            ],
            options={
                'indexes': [models.Index(fields=['feature_code', 'status'], name='strategy_an_feature_45d448_idx')],
                'constraints': [models.UniqueConstraint(fields=('feature_set', 'feature_code'), name='uniq_feature_value_in_set')],
            },
        ),
        migrations.AddIndex(
            model_name='featureset',
            index=models.Index(fields=['market_snapshot', 'status'], name='strategy_an_market__f051dd_idx'),
        ),
        migrations.AddIndex(
            model_name='featureset',
            index=models.Index(fields=['release_hash', 'definition_set_hash'], name='strategy_an_release_ec48fb_idx'),
        ),
        migrations.AddIndex(
            model_name='featureset',
            index=models.Index(fields=['trace_id'], name='strategy_an_trace_i_55d867_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyanalysisreleaseitem',
            index=models.Index(fields=['component_type', 'component_code'], name='strategy_an_compone_874a83_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyanalysisreleaseitem',
            index=models.Index(fields=['release', 'component_type', 'sort_order'], name='strategy_an_release_4e4459_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyanalysisreleaseitem',
            constraint=models.UniqueConstraint(fields=('release', 'component_type', 'component_code'), name='uniq_strategy_release_item_component'),
        ),
    ]
