# Generated by Django 5.2.15 on 2026-06-23 16:18

import hashlib
import json

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_feature_set_keys(apps, schema_editor):
    feature_set_model = apps.get_model("strategy_analysis", "FeatureSet")
    for feature_set in feature_set_model.objects.select_related("market_snapshot").all().iterator():
        manifest = {
            "market_snapshot_id": feature_set.market_snapshot_id,
            "snapshot_key": feature_set.market_snapshot.business_request_key,
            "feature_schema_version": feature_set.feature_schema_version,
            "definition_set_hash": feature_set.definition_set_hash,
        }
        canonical = json.dumps(manifest, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        feature_set_model.objects.filter(id=feature_set.id).update(
            feature_set_key=hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategy_analysis', '0003_remove_release_active_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureset',
            name='feature_schema_version',
            field=models.CharField(default='1.0', max_length=40, verbose_name='特征 schema 版本'),
        ),
        migrations.AddField(
            model_name='featureset',
            name='feature_set_key',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='特征集合稳定键'),
        ),
        migrations.RunPython(populate_feature_set_keys, migrations.RunPython.noop),
        migrations.AddField(
            model_name='featurevalue',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否为有效特征值'),
        ),
        migrations.CreateModel(
            name='AtomicSignalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_code', models.CharField(max_length=160, verbose_name='原子信号代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='分类')),
                ('default_direction', models.CharField(choices=[('bullish', '偏多'), ('bearish', '偏空'), ('neutral', '中性'), ('none', '无方向')], max_length=20, verbose_name='条件成立默认方向')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('is_required', models.BooleanField(default=False, verbose_name='失败是否阻断集合')),
                ('depends_on_feature_codes', models.JSONField(default=list, verbose_name='依赖特征代码')),
                ('output_type', models.CharField(choices=[('bool', '布尔'), ('decimal', '数值'), ('text', '文本'), ('json', '结构化数据')], max_length=40, verbose_name='输出类型')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['signal_code', 'status', 'enabled'], name='strategy_an_signal__81dc06_idx'), models.Index(fields=['algorithm_name', 'algorithm_version'], name='strategy_an_algorit_333a1c_idx')],
                'constraints': [models.UniqueConstraint(fields=('signal_code', 'definition_hash'), name='uniq_atomic_signal_definition_identity')],
            },
        ),
        migrations.CreateModel(
            name='AtomicSignalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_signal_set_key', models.CharField(max_length=80, unique=True, verbose_name='原子信号集合稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('feature_set_key', models.CharField(max_length=80, verbose_name='特征集合稳定键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('exchange', models.CharField(max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('analysis_close_time_utc', models.DateTimeField(verbose_name='分析收盘边界')),
                ('signal_schema_version', models.CharField(max_length=40, verbose_name='信号 schema 版本')),
                ('definition_set_hash', models.CharField(max_length=80, verbose_name='原子信号定义集指纹')),
                ('status', models.CharField(choices=[('created', '已创建'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='状态')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_domain_signal', models.BooleanField(default=False, verbose_name='允许领域层消费')),
                ('selected_definition_count', models.PositiveIntegerField(default=0, verbose_name='选择定义数量')),
                ('computed_count', models.PositiveIntegerField(default=0, verbose_name='完成计算数量')),
                ('valid_count', models.PositiveIntegerField(default=0, verbose_name='有效数量')),
                ('invalid_count', models.PositiveIntegerField(default=0, verbose_name='无效数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('required_failed_count', models.PositiveIntegerField(default=0, verbose_name='必需信号失败数量')),
                ('failure_ratio', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='失败比例')),
                ('failure_block_ratio', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='失败阻断比例')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='摘要')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('started_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='结束 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atomic_signal_sets', to='strategy_analysis.featureset')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atomic_signal_sets', to='market_data.marketsnapshot')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atomic_signal_sets', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='AtomicSignalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_code', models.CharField(max_length=160, verbose_name='原子信号代码')),
                ('direction', models.CharField(choices=[('bullish', '偏多'), ('bearish', '偏空'), ('neutral', '中性'), ('none', '无方向')], max_length=20, verbose_name='市场倾向')),
                ('strength', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='强度')),
                ('confidence', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='置信度')),
                ('status', models.CharField(choices=[('created', '已创建'), ('failed', '失败')], max_length=40, verbose_name='状态')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否有效')),
                ('definition_status', models.CharField(max_length=40, verbose_name='计算时定义状态')),
                ('definition_enabled', models.BooleanField(verbose_name='计算时定义开关')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('output_type', models.CharField(choices=[('bool', '布尔'), ('decimal', '数值'), ('text', '文本'), ('json', '结构化数据')], max_length=40, verbose_name='输出类型')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='布尔结果')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='数值结果')),
                ('value_text', models.CharField(blank=True, max_length=500, verbose_name='文本结果')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='结构化结果')),
                ('evidence_items', models.JSONField(default=list, verbose_name='机器可读证据')),
                ('evidence_text_zh', models.CharField(max_length=1000, verbose_name='中文证据')),
                ('used_feature_codes', models.JSONField(default=list, verbose_name='使用的特征代码')),
                ('used_feature_value_ids', models.JSONField(default=list, verbose_name='使用的特征值 ID')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('calculated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='计算 UTC 时间')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='计算耗时毫秒')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('atomic_signal_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='strategy_analysis.atomicsignaldefinition')),
                ('atomic_signal_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='strategy_analysis.atomicsignalset')),
            ],
        ),
        migrations.AddIndex(
            model_name='atomicsignalset',
            index=models.Index(fields=['feature_set', 'status'], name='strategy_an_feature_2e0319_idx'),
        ),
        migrations.AddIndex(
            model_name='atomicsignalset',
            index=models.Index(fields=['release_hash', 'definition_set_hash'], name='strategy_an_release_115289_idx'),
        ),
        migrations.AddIndex(
            model_name='atomicsignalset',
            index=models.Index(fields=['trace_id'], name='strategy_an_trace_i_c69923_idx'),
        ),
        migrations.AddIndex(
            model_name='atomicsignalvalue',
            index=models.Index(fields=['signal_code', 'status', 'is_valid'], name='strategy_an_signal__5aacc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='atomicsignalvalue',
            constraint=models.UniqueConstraint(fields=('atomic_signal_set', 'signal_code'), name='uniq_atomic_signal_value_in_set'),
        ),
        migrations.AlterField(
            model_name='featureset',
            name='feature_set_key',
            field=models.CharField(max_length=80, unique=True, verbose_name='特征集合稳定键'),
        ),
    ]
