# Generated by Django 5.2.15 on 2026-06-23 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategy_analysis', '0004_atomic_signal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSignalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_code', models.CharField(max_length=80, verbose_name='领域代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='分类')),
                ('output_mode', models.CharField(choices=[('directional', '方向型'), ('state', '状态型')], max_length=40, verbose_name='输出模式')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('is_required', models.BooleanField(default=True, verbose_name='失败是否阻断集合')),
                ('allowed_atomic_signal_codes', models.JSONField(default=list, verbose_name='允许原子信号代码')),
                ('required_atomic_signal_codes', models.JSONField(default=list, verbose_name='必需原子信号代码')),
                ('minimum_coverage_ratio', models.DecimalField(decimal_places=8, default=1, max_digits=10, verbose_name='最低覆盖率')),
                ('agreement_threshold', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='一致性阈值')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['domain_code', 'status', 'enabled'], name='strategy_an_domain__3815a5_idx'), models.Index(fields=['algorithm_name', 'algorithm_version'], name='strategy_an_algorit_31a530_idx')],
                'constraints': [models.UniqueConstraint(fields=('domain_code', 'definition_hash'), name='uniq_domain_signal_definition_identity')],
            },
        ),
        migrations.CreateModel(
            name='DomainSignalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_signal_set_key', models.CharField(max_length=80, unique=True, verbose_name='领域信号集合稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('atomic_signal_set_key', models.CharField(max_length=80, verbose_name='原子信号集合稳定键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('exchange', models.CharField(max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('analysis_close_time_utc', models.DateTimeField(verbose_name='分析收盘边界')),
                ('domain_schema_version', models.CharField(max_length=40, verbose_name='领域信号 schema 版本')),
                ('definition_set_hash', models.CharField(max_length=80, verbose_name='领域信号定义集指纹')),
                ('status', models.CharField(choices=[('created', '已创建'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='状态')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_market_regime', models.BooleanField(default=False, verbose_name='允许市场环境层消费')),
                ('selected_definition_count', models.PositiveIntegerField(default=0, verbose_name='选择定义数量')),
                ('computed_count', models.PositiveIntegerField(default=0, verbose_name='完成计算数量')),
                ('valid_count', models.PositiveIntegerField(default=0, verbose_name='有效数量')),
                ('invalid_count', models.PositiveIntegerField(default=0, verbose_name='无效数量')),
                ('required_failed_count', models.PositiveIntegerField(default=0, verbose_name='必需领域失败数量')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='摘要')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('started_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='结束 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('atomic_signal_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_signal_sets', to='strategy_analysis.atomicsignalset')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_signal_sets', to='market_data.marketsnapshot')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_signal_sets', to='strategy_analysis.strategyanalysisrelease')),
            ],
        ),
        migrations.CreateModel(
            name='DomainSignalValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_code', models.CharField(max_length=80, verbose_name='领域代码')),
                ('output_mode', models.CharField(choices=[('directional', '方向型'), ('state', '状态型')], max_length=40, verbose_name='输出模式')),
                ('direction', models.CharField(choices=[('bullish', '偏多'), ('bearish', '偏空'), ('neutral', '中性'), ('none', '无方向')], max_length=20, verbose_name='领域方向')),
                ('state_code', models.CharField(blank=True, max_length=80, verbose_name='状态代码')),
                ('strength', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='强度')),
                ('coverage_ratio', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='覆盖率')),
                ('agreement_ratio', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='一致性比例')),
                ('status', models.CharField(choices=[('created', '已创建'), ('failed', '失败')], max_length=40, verbose_name='状态')),
                ('is_valid', models.BooleanField(default=False, verbose_name='是否有效')),
                ('definition_status', models.CharField(max_length=40, verbose_name='计算时定义状态')),
                ('definition_enabled', models.BooleanField(verbose_name='计算时定义开关')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('used_atomic_signal_codes', models.JSONField(default=list, verbose_name='使用的原子信号代码')),
                ('used_atomic_signal_value_ids', models.JSONField(default=list, verbose_name='使用的原子信号值 ID')),
                ('evidence_items', models.JSONField(default=list, verbose_name='机器可读证据')),
                ('evidence_text_zh', models.CharField(max_length=1000, verbose_name='中文证据')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('calculated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='计算 UTC 时间')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='计算耗时毫秒')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('domain_signal_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='strategy_analysis.domainsignaldefinition')),
                ('domain_signal_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='strategy_analysis.domainsignalset')),
            ],
        ),
        migrations.AddIndex(
            model_name='domainsignalset',
            index=models.Index(fields=['atomic_signal_set', 'status'], name='strategy_an_atomic__2c4eac_idx'),
        ),
        migrations.AddIndex(
            model_name='domainsignalset',
            index=models.Index(fields=['release_hash', 'definition_set_hash'], name='strategy_an_release_3cc76d_idx'),
        ),
        migrations.AddIndex(
            model_name='domainsignalset',
            index=models.Index(fields=['trace_id'], name='strategy_an_trace_i_805bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='domainsignalvalue',
            index=models.Index(fields=['domain_code', 'status', 'is_valid'], name='strategy_an_domain__f0225e_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainsignalvalue',
            constraint=models.UniqueConstraint(fields=('domain_signal_set', 'domain_code'), name='uniq_domain_signal_value_in_set'),
        ),
    ]
