# Generated by Django 5.2.15 on 2026-06-23 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
        ('strategy_analysis', '0005_domain_signal_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegimeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_code', models.CharField(max_length=120, verbose_name='市场环境定义代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('input_schema_version', models.CharField(max_length=40, verbose_name='输入 schema 版本')),
                ('output_schema_version', models.CharField(max_length=40, verbose_name='输出 schema 版本')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('allowed_domain_codes', models.JSONField(default=list, verbose_name='允许领域代码')),
                ('required_domain_codes', models.JSONField(default=list, verbose_name='必须领域代码')),
                ('allowed_regime_codes', models.JSONField(default=list, verbose_name='允许环境分类代码')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['definition_code', 'status', 'enabled'], name='strategy_an_definit_8cb82d_idx'), models.Index(fields=['algorithm_name', 'algorithm_version'], name='strategy_an_algorit_8c4d96_idx')],
                'constraints': [models.UniqueConstraint(fields=('definition_code', 'definition_hash'), name='uniq_market_regime_definition_identity')],
            },
        ),
        migrations.CreateModel(
            name='MarketRegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_regime_snapshot_key', models.CharField(max_length=80, unique=True, verbose_name='市场环境快照稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('exchange', models.CharField(max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('analysis_close_time_utc', models.DateTimeField(verbose_name='分析收盘边界')),
                ('market_regime_schema_version', models.CharField(max_length=40, verbose_name='市场环境 schema 版本')),
                ('definition_set_hash', models.CharField(max_length=80, verbose_name='市场环境定义集指纹')),
                ('regime_code', models.CharField(blank=True, max_length=120, verbose_name='环境分类代码')),
                ('regime_scores', models.JSONField(default=dict, verbose_name='环境分类评分')),
                ('regime_confidence', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='分类明确程度')),
                ('classification_margin', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='分类区分度')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='状态')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_strategy_routing', models.BooleanField(default=False, verbose_name='允许策略路由消费')),
                ('definition_status', models.CharField(max_length=40, verbose_name='计算时定义状态')),
                ('definition_enabled', models.BooleanField(verbose_name='计算时定义开关')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('input_schema_version', models.CharField(max_length=40, verbose_name='输入 schema 版本')),
                ('output_schema_version', models.CharField(max_length=40, verbose_name='输出 schema 版本')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('used_domain_signal_codes', models.JSONField(default=list, verbose_name='实际使用领域代码')),
                ('used_domain_signal_value_ids', models.JSONField(default=list, verbose_name='实际使用领域值 ID')),
                ('evidence_items', models.JSONField(default=list, verbose_name='机器可读证据')),
                ('evidence_text_zh', models.CharField(max_length=1000, verbose_name='中文证据')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='摘要')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('calculated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='计算 UTC 时间')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='计算耗时毫秒')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('domain_signal_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_regime_snapshots', to='strategy_analysis.domainsignalset')),
                ('market_regime_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='strategy_analysis.marketregimedefinition')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_regime_snapshots', to='market_data.marketsnapshot')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_regime_snapshots', to='strategy_analysis.strategyanalysisrelease')),
            ],
            options={
                'indexes': [models.Index(fields=['domain_signal_set', 'status'], name='strategy_an_domain__382839_idx'), models.Index(fields=['release_hash', 'definition_set_hash'], name='strategy_an_release_c1d46a_idx'), models.Index(fields=['regime_code', 'status', 'is_usable'], name='strategy_an_regime__6a6971_idx'), models.Index(fields=['trace_id'], name='strategy_an_trace_i_a8138f_idx')],
            },
        ),
    ]
