# Generated by Django 5.2.15 on 2026-06-23 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0006_marketregimedefinition_marketregimesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_code', models.CharField(max_length=120, verbose_name='策略代码')),
                ('strategy_version', models.CharField(max_length=80, verbose_name='策略业务版本')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('input_schema_version', models.CharField(max_length=40, verbose_name='输入 schema 版本')),
                ('output_schema_version', models.CharField(max_length=40, verbose_name='输出 schema 版本')),
                ('params', models.JSONField(default=dict, verbose_name='参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('allowed_domain_codes', models.JSONField(default=list, verbose_name='允许领域代码')),
                ('required_domain_codes', models.JSONField(default=list, verbose_name='必须领域代码')),
                ('uses_input_weights', models.BooleanField(default=False, verbose_name='是否使用输入权重')),
                ('domain_input_weights', models.JSONField(default=dict, verbose_name='领域输入权重')),
                ('prediction_horizon', models.CharField(max_length=80, verbose_name='预测期限')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_code', 'status', 'enabled'], name='strategy_an_strateg_e125e2_idx'), models.Index(fields=['algorithm_name', 'algorithm_version'], name='strategy_an_algorit_5d64b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('strategy_code', 'strategy_version'), name='uniq_strategy_definition_version')],
            },
        ),
        migrations.CreateModel(
            name='StrategyRoutePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=120, verbose_name='路由策略代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('policy_version', models.CharField(max_length=80, verbose_name='路由策略版本')),
                ('condition_schema_version', models.CharField(max_length=40, verbose_name='条件 schema 版本')),
                ('rule_set_hash', models.CharField(max_length=80, verbose_name='规则集合指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('fallback_policy', models.CharField(choices=[('none', '不使用 fallback'), ('explicit', '使用明确 fallback')], default='none', max_length=40, verbose_name='fallback 策略')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('fallback_strategy_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fallback_route_policies', to='strategy_analysis.strategydefinition')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRouteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=120, verbose_name='规则代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('priority', models.PositiveIntegerField(verbose_name='优先级')),
                ('action', models.CharField(choices=[('select_strategy', '选择策略'), ('no_strategy', '不选择策略')], max_length=40, verbose_name='动作')),
                ('match_conditions', models.JSONField(default=dict, verbose_name='匹配条件')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('valid_from_utc', models.DateTimeField(blank=True, null=True, verbose_name='有效开始 UTC 时间')),
                ('valid_to_utc', models.DateTimeField(blank=True, null=True, verbose_name='有效结束 UTC 时间')),
                ('rule_hash', models.CharField(max_length=80, verbose_name='规则指纹')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('selected_strategy_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_rules', to='strategy_analysis.strategydefinition')),
                ('strategy_route_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='strategy_analysis.strategyroutepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRouteDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_route_decision_key', models.CharField(max_length=80, unique=True, verbose_name='策略路由决定稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('strategy_route_schema_version', models.CharField(max_length=40, verbose_name='策略路由 schema 版本')),
                ('route_outcome', models.CharField(blank=True, choices=[('selected', '已选择策略'), ('no_strategy', '不选择策略')], max_length=40, verbose_name='路由结果')),
                ('matched_conditions', models.JSONField(default=dict, verbose_name='命中条件')),
                ('selection_reason', models.CharField(max_length=1000, verbose_name='选择原因')),
                ('fallback_used', models.BooleanField(default=False, verbose_name='是否使用 fallback')),
                ('fallback_reason', models.CharField(blank=True, max_length=500, verbose_name='fallback 原因')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='状态')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_strategy_signal', models.BooleanField(default=False, verbose_name='允许策略信号消费')),
                ('policy_status', models.CharField(max_length=40, verbose_name='计算时 Policy 状态')),
                ('policy_enabled', models.BooleanField(verbose_name='计算时 Policy 开关')),
                ('policy_version', models.CharField(max_length=80, verbose_name='Policy 版本')),
                ('condition_schema_version', models.CharField(max_length=40, verbose_name='条件 schema 版本')),
                ('rule_set_hash', models.CharField(max_length=80, verbose_name='规则集合指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='Policy 定义指纹')),
                ('eligible_strategy_definition_ids', models.JSONField(default=list, verbose_name='候选策略定义 ID')),
                ('evidence_items', models.JSONField(default=list, verbose_name='机器可读证据')),
                ('evidence_text_zh', models.CharField(max_length=1000, verbose_name='中文证据')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='摘要')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('analysis_close_time_utc', models.DateTimeField(verbose_name='分析收盘边界')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('calculated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='计算 UTC 时间')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='计算耗时毫秒')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('market_regime_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_route_decisions', to='strategy_analysis.marketregimesnapshot')),
                ('selected_strategy_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_decisions', to='strategy_analysis.strategydefinition')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_route_decisions', to='strategy_analysis.strategyanalysisrelease')),
                ('strategy_route_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='strategy_analysis.strategyroutepolicy')),
                ('matched_strategy_route_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='strategy_analysis.strategyrouterule')),
            ],
        ),
        migrations.AddIndex(
            model_name='strategyroutepolicy',
            index=models.Index(fields=['policy_code', 'status', 'enabled'], name='strategy_an_policy__0e346f_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyroutepolicy',
            constraint=models.UniqueConstraint(fields=('policy_code', 'policy_version'), name='uniq_strategy_route_policy_version'),
        ),
        migrations.AddIndex(
            model_name='strategyrouterule',
            index=models.Index(fields=['strategy_route_policy', 'priority'], name='strategy_an_strateg_630d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyrouterule',
            index=models.Index(fields=['status', 'enabled'], name='strategy_an_status_8dd341_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyrouterule',
            constraint=models.UniqueConstraint(fields=('strategy_route_policy', 'rule_code'), name='uniq_strategy_route_rule_code'),
        ),
        migrations.AddIndex(
            model_name='strategyroutedecision',
            index=models.Index(fields=['market_regime_snapshot', 'status'], name='strategy_an_market__ab0441_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyroutedecision',
            index=models.Index(fields=['release_hash', 'definition_hash'], name='strategy_an_release_34f220_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyroutedecision',
            index=models.Index(fields=['route_outcome', 'status', 'is_usable'], name='strategy_an_route_o_dde6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='strategyroutedecision',
            index=models.Index(fields=['trace_id'], name='strategy_an_trace_i_ef78aa_idx'),
        ),
    ]
