# Generated by Django 5.2.15 on 2026-06-23 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0007_strategydefinition_strategyroutepolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_signal_key', models.CharField(max_length=80, unique=True, verbose_name='策略信号稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('strategy_signal_schema_version', models.CharField(max_length=40, verbose_name='策略信号 schema 版本')),
                ('strategy_code', models.CharField(max_length=120, verbose_name='策略代码')),
                ('strategy_version', models.CharField(max_length=80, verbose_name='策略业务版本')),
                ('direction', models.CharField(choices=[('bullish', '偏多'), ('bearish', '偏空'), ('neutral', '中性'), ('none', '无有效方向')], max_length=20, verbose_name='策略方向')),
                ('strength', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='策略强度')),
                ('confidence', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='策略置信评分')),
                ('confidence_semantics', models.CharField(blank=True, max_length=80, verbose_name='置信评分语义')),
                ('prediction_horizon', models.CharField(blank=True, max_length=80, verbose_name='预测期限')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='状态')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_strategy_signal_quality', models.BooleanField(default=False, verbose_name='允许策略信号质量层消费')),
                ('definition_status', models.CharField(max_length=40, verbose_name='计算时 Definition 状态')),
                ('definition_enabled', models.BooleanField(verbose_name='计算时 Definition 开关')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('input_schema_version', models.CharField(max_length=40, verbose_name='输入 schema 版本')),
                ('output_schema_version', models.CharField(max_length=40, verbose_name='输出 schema 版本')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('used_domain_signal_codes', models.JSONField(default=list, verbose_name='实际使用领域代码')),
                ('used_domain_signal_value_ids', models.JSONField(default=list, verbose_name='实际使用领域值 ID')),
                ('actual_input_weights', models.JSONField(default=dict, verbose_name='实际输入权重')),
                ('aggregation_snapshot', models.JSONField(default=dict, verbose_name='聚合摘要')),
                ('conflict_snapshot', models.JSONField(default=dict, verbose_name='冲突摘要')),
                ('evidence_items', models.JSONField(default=list, verbose_name='机器可读证据')),
                ('evidence_text_zh', models.CharField(max_length=1000, verbose_name='中文证据')),
                ('payload_summary', models.JSONField(blank=True, default=dict, verbose_name='摘要')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('analysis_close_time_utc', models.DateTimeField(verbose_name='分析收盘边界')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('calculated_at_utc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='计算 UTC 时间')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='计算耗时毫秒')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('domain_signal_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signals', to='strategy_analysis.domainsignalset')),
                ('market_regime_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signals', to='strategy_analysis.marketregimesnapshot')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signals', to='strategy_analysis.strategyanalysisrelease')),
                ('strategy_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signals', to='strategy_analysis.strategydefinition')),
                ('strategy_route_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signals', to='strategy_analysis.strategyroutedecision')),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_route_decision', 'status'], name='strategy_an_strateg_a0e3c8_idx'), models.Index(fields=['release_hash', 'definition_hash'], name='strategy_an_release_69d08a_idx'), models.Index(fields=['direction', 'status', 'is_usable'], name='strategy_an_directi_4c9218_idx'), models.Index(fields=['trace_id'], name='strategy_an_trace_i_23a668_idx')],
            },
        ),
    ]
