# Generated by Django 5.2.15 on 2026-06-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0008_strategysignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySignalQualityRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_set_code', models.CharField(max_length=120, verbose_name='质量规则集代码')),
                ('rule_set_version', models.CharField(max_length=80, verbose_name='质量规则集版本')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('quality_schema_version', models.CharField(max_length=40, verbose_name='质量 schema 版本')),
                ('max_staleness_seconds', models.PositiveIntegerField(default=0, verbose_name='最大允许陈旧秒数')),
                ('warning_blocks_decision', models.BooleanField(default=False, verbose_name='warning 是否阻断 DecisionSnapshot')),
                ('fail_alert_enabled', models.BooleanField(default=True, verbose_name='失败是否写告警')),
                ('warning_alert_enabled', models.BooleanField(default=False, verbose_name='warning 是否写告警')),
                ('consecutive_failure_threshold', models.PositiveIntegerField(default=0, verbose_name='连续失败告警阈值')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='规则参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='规则参数指纹')),
                ('rule_set_hash', models.CharField(max_length=80, verbose_name='质量规则集指纹')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['rule_set_code', 'status', 'enabled'], name='strategy_an_rule_se_abc1ea_idx'), models.Index(fields=['rule_set_hash'], name='strategy_an_rule_se_017fa0_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule_set_code', 'rule_set_version'), name='uniq_strategy_signal_quality_rule_set_version')],
            },
        ),
        migrations.CreateModel(
            name='StrategySignalQualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_result_key', models.CharField(max_length=80, unique=True, verbose_name='质量结果稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('strategy_signal_key', models.CharField(max_length=80, verbose_name='策略信号稳定键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('strategy_code', models.CharField(max_length=120, verbose_name='策略代码')),
                ('strategy_version', models.CharField(max_length=80, verbose_name='策略业务版本')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('quality_schema_version', models.CharField(max_length=40, verbose_name='质量 schema 版本')),
                ('quality_rule_set_version', models.CharField(max_length=80, verbose_name='质量规则集版本')),
                ('quality_rule_set_hash', models.CharField(max_length=80, verbose_name='质量规则集指纹')),
                ('validation_mode', models.CharField(choices=[('live', '正式运行'), ('replay', '回放'), ('backfill', '补算'), ('manual', '人工')], max_length=40, verbose_name='验证模式')),
                ('reference_time_utc', models.DateTimeField(verbose_name='参考 UTC 时间')),
                ('validation_as_of_utc', models.DateTimeField(verbose_name='验证 UTC 时间')),
                ('market_as_of_utc', models.DateTimeField(blank=True, null=True, verbose_name='市场事实 UTC 时间')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='流程状态')),
                ('quality_status', models.CharField(blank=True, choices=[('passed', '通过'), ('warning', '警告'), ('failed', '未通过')], max_length=40, verbose_name='质量状态')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='质量评分')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_decision_snapshot', models.BooleanField(default=False, verbose_name='允许目标仓位决策消费')),
                ('issue_count', models.PositiveIntegerField(default=0, verbose_name='问题数量')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='warning 数量')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='error 数量')),
                ('critical_count', models.PositiveIntegerField(default=0, verbose_name='critical 数量')),
                ('blocked_reason', models.CharField(blank=True, max_length=120, verbose_name='阻断原因')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('check_summary', models.JSONField(blank=True, default=dict, verbose_name='检查摘要')),
                ('summary_text_zh', models.CharField(max_length=1000, verbose_name='中文摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('domain_signal_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signal_quality_results', to='strategy_analysis.domainsignalset')),
                ('market_regime_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signal_quality_results', to='strategy_analysis.marketregimesnapshot')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signal_quality_results', to='strategy_analysis.strategyanalysisrelease')),
                ('strategy_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signal_quality_results', to='strategy_analysis.strategydefinition')),
                ('strategy_route_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_signal_quality_results', to='strategy_analysis.strategyroutedecision')),
                ('strategy_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_results', to='strategy_analysis.strategysignal')),
                ('strategy_signal_quality_rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_results', to='strategy_analysis.strategysignalqualityruleset')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySignalQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_code', models.CharField(max_length=120, verbose_name='问题代码')),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], max_length=40, verbose_name='严重程度')),
                ('check_group', models.CharField(max_length=120, verbose_name='检查分组')),
                ('check_name', models.CharField(max_length=120, verbose_name='检查名称')),
                ('field_name', models.CharField(blank=True, max_length=120, verbose_name='字段名')),
                ('message_zh', models.CharField(max_length=500, verbose_name='中文说明')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='问题详情')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('quality_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='strategy_analysis.strategysignalqualityresult')),
            ],
            options={
                'indexes': [models.Index(fields=['quality_result', 'severity'], name='strategy_an_quality_f7861f_idx'), models.Index(fields=['issue_code', 'severity'], name='strategy_an_issue_c_d4346b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='strategysignalqualityresult',
            index=models.Index(fields=['strategy_signal', 'status'], name='strategy_an_strateg_c1257b_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysignalqualityresult',
            index=models.Index(fields=['release_hash', 'quality_rule_set_hash'], name='strategy_an_release_992ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysignalqualityresult',
            index=models.Index(fields=['quality_status', 'allows_decision_snapshot'], name='strategy_an_quality_842766_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysignalqualityresult',
            index=models.Index(fields=['trace_id'], name='strategy_an_trace_i_564329_idx'),
        ),
    ]
