# Generated by Django 5.2.15 on 2026-06-24 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0009_strategysignalqualityruleset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionPolicyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=120, verbose_name='目标仓位决策规则代码')),
                ('policy_version', models.CharField(max_length=80, verbose_name='目标仓位决策规则版本')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('input_schema_version', models.CharField(max_length=40, verbose_name='输入 schema 版本')),
                ('output_schema_version', models.CharField(max_length=40, verbose_name='输出 schema 版本')),
                ('target_schema_version', models.CharField(max_length=40, verbose_name='目标仓位 schema 版本')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='规则参数')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '可用'), ('deprecated', '已弃用'), ('retired', '已退役'), ('disabled', '已禁用')], default='draft', max_length=40, verbose_name='生命周期状态')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['policy_code', 'status', 'enabled'], name='strategy_an_policy__45d5e2_idx'), models.Index(fields=['definition_hash'], name='strategy_an_definit_539c2c_idx'), models.Index(fields=['algorithm_name', 'algorithm_version'], name='strategy_an_algorit_f500c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('policy_code', 'policy_version'), name='uniq_decision_policy_definition_version')],
            },
        ),
        migrations.CreateModel(
            name='DecisionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_snapshot_key', models.CharField(max_length=80, unique=True, verbose_name='目标仓位快照稳定键')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('release_hash', models.CharField(max_length=80, verbose_name='版本包指纹')),
                ('strategy_code', models.CharField(max_length=120, verbose_name='策略代码')),
                ('strategy_version', models.CharField(max_length=80, verbose_name='策略业务版本')),
                ('policy_code', models.CharField(max_length=120, verbose_name='决策规则代码')),
                ('policy_version', models.CharField(max_length=80, verbose_name='决策规则版本')),
                ('algorithm_name', models.CharField(max_length=120, verbose_name='算法名称')),
                ('algorithm_version', models.CharField(max_length=80, verbose_name='算法版本')),
                ('params_hash', models.CharField(max_length=80, verbose_name='参数指纹')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('target_schema_version', models.CharField(max_length=40, verbose_name='目标仓位 schema 版本')),
                ('target_intent', models.CharField(blank=True, choices=[('TARGET_POSITION', '目标仓位'), ('NO_TARGET_CHANGE', '目标不变'), ('NO_TRADE', '本轮不交易')], max_length=40, verbose_name='目标意图')),
                ('target_position_ratio', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='目标总仓位比例')),
                ('target_confidence', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='目标仓位置信评分')),
                ('target_reason_code', models.CharField(blank=True, max_length=120, verbose_name='目标原因代码')),
                ('target_reason_summary_zh', models.CharField(blank=True, max_length=1000, verbose_name='中文原因摘要')),
                ('decision_calculation_snapshot', models.JSONField(blank=True, default=dict, verbose_name='计算快照')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, verbose_name='输入快照')),
                ('evidence_summary', models.JSONField(blank=True, default=dict, verbose_name='证据摘要')),
                ('market_as_of_utc', models.DateTimeField(blank=True, null=True, verbose_name='市场事实 UTC 时间')),
                ('analysis_close_time_utc', models.DateTimeField(blank=True, null=True, verbose_name='分析收盘边界')),
                ('expires_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='过期 UTC 时间')),
                ('status', models.CharField(choices=[('created', '已创建'), ('blocked', '阻断'), ('failed', '失败'), ('unknown', '未知')], max_length=40, verbose_name='流程状态')),
                ('is_usable', models.BooleanField(default=False, verbose_name='是否可用')),
                ('allows_order_plan', models.BooleanField(default=False, verbose_name='允许 OrderPlan 消费')),
                ('blocked_reason', models.CharField(blank=True, max_length=120, verbose_name='阻断原因')),
                ('error_code', models.CharField(blank=True, max_length=120, verbose_name='错误代码')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='错误摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('decision_policy_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_snapshots', to='strategy_analysis.decisionpolicydefinition')),
                ('strategy_analysis_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_snapshots', to='strategy_analysis.strategyanalysisrelease')),
                ('strategy_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_snapshots', to='strategy_analysis.strategysignal')),
                ('strategy_signal_quality_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_snapshots', to='strategy_analysis.strategysignalqualityresult')),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_signal_quality_result', 'status'], name='strategy_an_strateg_15b4f0_idx'), models.Index(fields=['release_hash', 'definition_hash'], name='strategy_an_release_234a79_idx'), models.Index(fields=['target_intent', 'allows_order_plan'], name='strategy_an_target__3a6a03_idx'), models.Index(fields=['expires_at_utc'], name='strategy_an_expires_d4b2f9_idx'), models.Index(fields=['trace_id'], name='strategy_an_trace_i_4cce48_idx')],
            },
        ),
    ]
