# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_analysis", "0010_decisionpolicydefinition_decisionsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategysignal",
            name="trade_price_condition",
            field=models.JSONField(blank=True, default=dict, verbose_name="策略价格条件"),
        ),
        migrations.AddField(
            model_name="decisionsnapshot",
            name="frozen_trade_price_condition",
            field=models.JSONField(blank=True, default=dict, verbose_name="冻结策略价格条件"),
        ),
        migrations.AddField(
            model_name="decisionsnapshot",
            name="frozen_trade_price_condition_hash",
            field=models.CharField(blank=True, max_length=80, verbose_name="冻结策略价格条件指纹"),
        ),
    ]
