# Generated by Django 5.2.15 on 2026-06-30 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0011_strategy_price_condition_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyAnalysisWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_code', models.CharField(max_length=120, unique=True, verbose_name='配置工作区代码')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='展示名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('active', '可用'), ('archived', '已归档')], default='active', max_length=40, verbose_name='状态')),
                ('default_slot', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='默认工作区槽位')),
                ('created_by', models.CharField(blank=True, max_length=120, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=120, verbose_name='最后更新人')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace_code', 'status'], name='strategy_an_workspa_9405dd_idx'), models.Index(fields=['default_slot', 'status'], name='strategy_an_default_7079dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyAnalysisWorkspaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('feature_definition', '特征定义'), ('atomic_signal_definition', '原子信号定义'), ('domain_signal_definition', '领域定义'), ('market_regime_definition', '市场环境定义'), ('strategy_route_policy', '策略路由策略'), ('strategy_route_rule', '策略路由规则'), ('strategy_definition', '策略定义'), ('strategy_signal_quality_rule_set', '策略信号质量规则集'), ('decision_policy_definition', '目标仓位决策定义')], max_length=80, verbose_name='组件类型')),
                ('component_object_id', models.PositiveIntegerField(verbose_name='组件对象 ID')),
                ('component_code', models.CharField(max_length=160, verbose_name='组件代码')),
                ('component_version', models.CharField(blank=True, max_length=80, verbose_name='组件版本')),
                ('definition_hash', models.CharField(max_length=80, verbose_name='定义指纹')),
                ('inclusion_managed', models.BooleanField(default=True, verbose_name='是否支持纳入状态')),
                ('is_included', models.BooleanField(default=True, verbose_name='是否纳入当前组合')),
                ('selection_reason', models.CharField(blank=True, max_length=500, verbose_name='选择原因')),
                ('updated_by', models.CharField(blank=True, max_length=120, verbose_name='最后更新人')),
                ('trace_id', models.CharField(blank=True, max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(blank=True, max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='strategy_analysis.strategyanalysisworkspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'component_type', 'is_included'], name='strategy_an_workspa_73764f_idx'), models.Index(fields=['component_type', 'component_code'], name='strategy_an_compone_3c27c6_idx'), models.Index(fields=['definition_hash'], name='strategy_an_definit_565386_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'component_type', 'component_code'), name='uniq_strategy_workspace_item_code')],
            },
        ),
    ]
