# Generated by Django 5.2.15 on 2026-07-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0012_strategyanalysisworkspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyBacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=191, unique=True, verbose_name='回测运行键')),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('succeeded', '已完成'), ('blocked', '已阻断'), ('failed', '失败')], db_index=True, default='queued', max_length=40, verbose_name='状态')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('strategy_analysis_release_hash', models.CharField(blank=True, max_length=80, verbose_name='策略版本包指纹')),
                ('start_analysis_close_time_utc', models.DateTimeField(verbose_name='开始分析边界 UTC')),
                ('end_analysis_close_time_utc', models.DateTimeField(verbose_name='结束分析边界 UTC')),
                ('lookback_4h_count', models.PositiveIntegerField(default=500, verbose_name='4h 回看数量')),
                ('lookback_1d_count', models.PositiveIntegerField(default=500, verbose_name='1d 回看数量')),
                ('initial_equity', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='初始资金')),
                ('fee_rate', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='手续费率')),
                ('no_target_policy', models.CharField(default='hold', max_length=40, verbose_name='无目标仓位策略')),
                ('business_request_prefix', models.CharField(max_length=120, verbose_name='业务请求前缀')),
                ('requested_by', models.CharField(blank=True, max_length=120, verbose_name='请求人')),
                ('celery_task_id', models.CharField(blank=True, max_length=120, verbose_name='Celery 任务 ID')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
                ('error_message', models.TextField(blank=True, verbose_name='错误摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('started_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='结束 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('strategy_analysis_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtest_runs', to='strategy_analysis.strategyanalysisrelease')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at_utc'], name='strategy_an_status_fb1220_idx'), models.Index(fields=['strategy_analysis_release', 'created_at_utc'], name='strategy_an_strateg_6a34cd_idx'), models.Index(fields=['trace_id'], name='strategy_an_trace_i_196b0e_idx')],
            },
        ),
    ]
