# Generated by Django 5.2.15 on 2026-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0013_strategybacktestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategybacktestrun',
            name='progress_completed_periods',
            field=models.PositiveIntegerField(default=0, verbose_name='进度已完成周期数'),
        ),
        migrations.AddField(
            model_name='strategybacktestrun',
            name='progress_current_analysis_close_time_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='当前处理分析边界 UTC'),
        ),
        migrations.AddField(
            model_name='strategybacktestrun',
            name='progress_last_reason_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='最近周期原因代码'),
        ),
        migrations.AddField(
            model_name='strategybacktestrun',
            name='progress_last_status',
            field=models.CharField(blank=True, max_length=80, verbose_name='最近周期状态'),
        ),
        migrations.AddField(
            model_name='strategybacktestrun',
            name='progress_total_periods',
            field=models.PositiveIntegerField(default=0, verbose_name='进度总周期数'),
        ),
        migrations.AddField(
            model_name='strategybacktestrun',
            name='progress_updated_at_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='进度更新 UTC 时间'),
        ),
    ]
