# Generated by Codex on 2026-07-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_analysis", "0014_strategybacktestrun_progress_completed_periods_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyBacktestPeriodResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_index", models.PositiveIntegerField(verbose_name="回测周期序号")),
                ("analysis_close_time_utc", models.DateTimeField(verbose_name="分析边界 UTC")),
                ("status", models.CharField(max_length=80, verbose_name="周期状态")),
                ("reason_code", models.CharField(blank=True, max_length=120, verbose_name="原因代码")),
                ("market_regime", models.CharField(blank=True, max_length=120, verbose_name="市场环境")),
                ("selected_strategy", models.CharField(blank=True, max_length=120, verbose_name="选中策略")),
                ("signal_direction", models.CharField(blank=True, max_length=40, verbose_name="策略方向")),
                (
                    "previous_position_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="调仓前仓位比例",
                    ),
                ),
                (
                    "target_position_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="目标仓位比例",
                    ),
                ),
                (
                    "position_change_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="仓位变化比例",
                    ),
                ),
                (
                    "position_change_notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=38,
                        null=True,
                        verbose_name="仓位变化名义金额",
                    ),
                ),
                (
                    "position_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="调仓后仓位比例",
                    ),
                ),
                (
                    "simulated_execution_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=38,
                        null=True,
                        verbose_name="模拟成交价",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=38,
                        null=True,
                        verbose_name="周期收盘价",
                    ),
                ),
                (
                    "kline_return_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="K线涨跌比例",
                    ),
                ),
                (
                    "period_return_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="周期收益比例",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=38,
                        null=True,
                        verbose_name="模拟手续费",
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=38,
                        null=True,
                        verbose_name="周期结束权益",
                    ),
                ),
                (
                    "drawdown_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=18,
                        max_digits=20,
                        null=True,
                        verbose_name="当前回撤比例",
                    ),
                ),
                ("created_at_utc", models.DateTimeField(auto_now_add=True, verbose_name="创建 UTC 时间")),
                (
                    "strategy_backtest_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_results",
                        to="strategy_analysis.strategybacktestrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="strategybacktestperiodresult",
            constraint=models.UniqueConstraint(
                fields=("strategy_backtest_run", "period_index"),
                name="uniq_strategy_backtest_period_index",
            ),
        ),
        migrations.AddIndex(
            model_name="strategybacktestperiodresult",
            index=models.Index(
                fields=["strategy_backtest_run", "period_index"],
                name="strategy_an_strateg_334d1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="strategybacktestperiodresult",
            index=models.Index(
                fields=["strategy_backtest_run", "analysis_close_time_utc"],
                name="strategy_an_strateg_27ee46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="strategybacktestperiodresult",
            index=models.Index(fields=["selected_strategy"], name="strategy_an_selecte_6e034a_idx"),
        ),
    ]
