# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_analysis", "0015_strategybacktestperiodresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategybacktestrun",
            name="leverage",
            field=models.DecimalField(decimal_places=18, default=1, max_digits=30, verbose_name="回测杠杆倍数"),
        ),
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="leverage",
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name="回测杠杆倍数"),
        ),
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="effective_position_ratio",
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name="杠杆后有效仓位比例"),
        ),
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="effective_position_change_ratio",
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name="杠杆后有效仓位变化比例"),
        ),
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="effective_position_notional",
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name="杠杆后有效仓位名义金额"),
        ),
    ]
