# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy_analysis", "0016_strategy_backtest_leverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="is_liquidated",
            field=models.BooleanField(default=False, verbose_name="是否爆仓"),
        ),
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="liquidation_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=18,
                max_digits=38,
                null=True,
                verbose_name="估算强平价",
            ),
        ),
        migrations.AddField(
            model_name="strategybacktestperiodresult",
            name="liquidation_reason_code",
            field=models.CharField(blank=True, max_length=120, verbose_name="爆仓原因代码"),
        ),
    ]
