# Generated by Django 5.2.15 on 2026-07-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_analysis', '0017_strategy_backtest_liquidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategybacktestperiodresult',
            name='analysis_object_ids',
            field=models.JSONField(blank=True, default=dict, verbose_name='分析链路对象 ID'),
        ),
        migrations.AddField(
            model_name='strategybacktestperiodresult',
            name='analysis_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='分析链路摘要'),
        ),
    ]
