# Generated by Django 5.2.15 on 2026-06-28 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0002_ordersubmissionattempt_limit_fields'),
        ('execution_preparation', '0003_preparedorderintent_limit_fields'),
        ('order_plan', '0004_candidateorderintent_limit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancelAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_cancel_attempt_key', models.CharField(max_length=191, unique=True, verbose_name='撤单尝试幂等键')),
                ('business_request_key', models.CharField(max_length=191, verbose_name='业务幂等键')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('endpoint_family', models.CharField(blank=True, max_length=40, verbose_name='Gateway endpoint family')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('client_order_id', models.CharField(blank=True, max_length=120, verbose_name='Binance clientOrderId')),
                ('exchange_order_id', models.CharField(blank=True, max_length=120, verbose_name='交易所订单 ID')),
                ('closeout_time_utc', models.DateTimeField(verbose_name='收尾 UTC 时间')),
                ('limit_valid_until_utc', models.DateTimeField(verbose_name='LIMIT 有效截止 UTC 时间')),
                ('cancel_reason_code', models.CharField(max_length=120, verbose_name='撤单原因代码')),
                ('cancel_status', models.CharField(choices=[('canceling', '撤单中'), ('accepted', '撤单请求已被交易所接受'), ('not_found', '交易所明确未找到订单'), ('unknown', '撤单结果未知'), ('failed_before_cancel', '撤单前失败'), ('blocked_before_cancel', '撤单前阻断')], max_length=40, verbose_name='撤单状态')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='结果原因代码')),
                ('request_sent', models.BooleanField(default=False, verbose_name='请求是否已发出')),
                ('response_received', models.BooleanField(default=False, verbose_name='是否收到响应')),
                ('gateway_attempt_count', models.PositiveIntegerField(default=0, verbose_name='Gateway 技术尝试次数')),
                ('cancel_request', models.JSONField(blank=True, default=dict, verbose_name='冻结撤单请求')),
                ('request_payload_hash', models.CharField(blank=True, max_length=80, verbose_name='撤单请求 hash')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP 状态码')),
                ('binance_error_code', models.CharField(blank=True, max_length=80, verbose_name='Binance 错误码')),
                ('sanitized_error_message', models.CharField(blank=True, max_length=500, verbose_name='脱敏错误摘要')),
                ('sanitized_response', models.JSONField(blank=True, default=dict, verbose_name='脱敏交易所响应')),
                ('response_hash', models.CharField(blank=True, max_length=80, verbose_name='交易所响应 hash')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('rate_limit_metadata', models.JSONField(blank=True, default=dict, verbose_name='限频元数据')),
                ('alert_event_ids', models.JSONField(blank=True, default=list, verbose_name='AlertEvent ID')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('started_at_utc', models.DateTimeField(verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='完成 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('active_lock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cancel_attempts', to='order_plan.orderplanactivelock')),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cancel_attempts', to='order_plan.orderplan')),
                ('order_submission_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cancel_attempts', to='execution.ordersubmissionattempt')),
                ('prepared_order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_cancel_attempts', to='execution_preparation.preparedorderintent')),
            ],
            options={
                'indexes': [models.Index(fields=['order_submission_attempt', 'cancel_status'], name='order_lifec_order_s_a3628e_idx'), models.Index(fields=['cancel_status', 'created_at_utc'], name='order_lifec_cancel__bbde92_idx'), models.Index(fields=['market_type', 'account_domain', 'symbol'], name='order_lifec_market__65ff92_idx'), models.Index(fields=['active_lock'], name='order_lifec_active__c73c27_idx'), models.Index(fields=['trace_id'], name='order_lifec_trace_i_bcfb5c_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_submission_attempt', 'closeout_time_utc', 'cancel_reason_code'), name='uniq_order_cancel_attempt_closeout_reason')],
            },
        ),
    ]
