# Generated by Django 5.2.15 on 2026-06-24 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('binance_account_sync', '0001_initial'),
        ('order_plan', '0003_alter_orderplan_status'),
        ('price_snapshot', '0001_initial'),
        ('risk_check', '0002_alter_approvedorderintent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPreparationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_request_key', models.CharField(max_length=191, verbose_name='业务幂等键')),
                ('execution_preparation_key', models.CharField(max_length=191, unique=True, verbose_name='执行准备幂等键')),
                ('status', models.CharField(choices=[('PREPARING', '准备中'), ('PREPARED', '已准备'), ('BLOCKED', '已阻断'), ('FAILED', '失败'), ('EXPIRED', '已过期')], max_length=40, verbose_name='执行准备状态')),
                ('reason_code', models.CharField(max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('price_snapshot_hash', models.CharField(max_length=80, verbose_name='价格快照 hash')),
                ('binance_snapshot_set_hash', models.CharField(max_length=80, verbose_name='账户快照集合 hash')),
                ('reference_mark_price', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='参考 mark price')),
                ('best_bid_price', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='最优买价')),
                ('best_bid_quantity', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='最优买量')),
                ('best_ask_price', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='最优卖价')),
                ('best_ask_quantity', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='最优卖量')),
                ('selected_live_price', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='执行侧参考盘口价')),
                ('selected_live_price_side', models.CharField(blank=True, max_length=20, verbose_name='选中盘口侧')),
                ('price_deviation_ratio', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True, verbose_name='价格偏差比例')),
                ('price_deviation_bps', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='价格偏差 bps')),
                ('price_deviation_limit_bps', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='价格偏差上限 bps')),
                ('live_price_requested_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='盘口请求 UTC 时间')),
                ('live_price_observed_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='盘口观测 UTC 时间')),
                ('gateway_result_metadata', models.JSONField(blank=True, default=dict, verbose_name='Gateway 结果元数据')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='配置快照')),
                ('input_hash', models.CharField(max_length=80, verbose_name='输入 hash')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='执行准备证据')),
                ('alert_event_ids', models.JSONField(blank=True, default=list, verbose_name='AlertEvent ID')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('started_at_utc', models.DateTimeField(verbose_name='开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='完成 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('account_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='binance_account_sync.binanceaccountsnapshot')),
                ('active_lock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='order_plan.orderplanactivelock')),
                ('approved_order_intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_result', to='risk_check.approvedorderintent')),
                ('binance_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='binance_account_sync.binancesyncrun')),
                ('candidate_order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='order_plan.candidateorderintent')),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='order_plan.orderplan')),
                ('position_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='binance_account_sync.binancepositionsnapshot')),
                ('price_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='price_snapshot.pricesnapshot')),
                ('risk_check_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='risk_check.riskcheckresult')),
                ('symbol_rule_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_preparation_results', to='binance_account_sync.binancesymbolrulesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='PreparedOrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared_order_intent_key', models.CharField(max_length=191, unique=True, verbose_name='待提交请求幂等键')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('position_mode', models.CharField(max_length=40, verbose_name='持仓模式')),
                ('position_side', models.CharField(max_length=20, verbose_name='持仓方向')),
                ('side', models.CharField(max_length=10, verbose_name='订单方向')),
                ('order_type', models.CharField(max_length=40, verbose_name='订单类型')),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='冻结数量')),
                ('quantity_unit', models.CharField(max_length=40, verbose_name='数量单位')),
                ('reduce_only', models.BooleanField(verbose_name='reduceOnly')),
                ('time_in_force', models.CharField(blank=True, max_length=40, verbose_name='timeInForce')),
                ('client_order_id', models.CharField(max_length=36, unique=True, verbose_name='Binance clientOrderId')),
                ('idempotency_key', models.CharField(max_length=191, unique=True, verbose_name='订单提交幂等键')),
                ('reference_mark_price', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='参考 mark price')),
                ('selected_live_price', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='执行侧参考盘口价')),
                ('price_deviation_bps', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='价格偏差 bps')),
                ('prepared_at_utc', models.DateTimeField(verbose_name='准备完成 UTC 时间')),
                ('expires_at_utc', models.DateTimeField(verbose_name='过期 UTC 时间')),
                ('status', models.CharField(choices=[('prepared', '待提交'), ('expired', '已过期'), ('consumed', '已进入执行')], default='prepared', max_length=40, verbose_name='状态')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='配置快照')),
                ('evidence_hash', models.CharField(max_length=80, verbose_name='证据 hash')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('account_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='binance_account_sync.binanceaccountsnapshot')),
                ('binance_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='binance_account_sync.binancesyncrun')),
                ('execution_preparation_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intent', to='execution_preparation.executionpreparationresult')),
                ('position_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='binance_account_sync.binancepositionsnapshot')),
                ('price_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='price_snapshot.pricesnapshot')),
                ('source_approved_order_intent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intent', to='risk_check.approvedorderintent')),
                ('source_candidate_order_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='order_plan.candidateorderintent')),
                ('source_order_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='order_plan.orderplan')),
                ('source_risk_check_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='risk_check.riskcheckresult')),
                ('symbol_rule_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_order_intents', to='binance_account_sync.binancesymbolrulesnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='executionpreparationresult',
            index=models.Index(fields=['status', 'created_at_utc'], name='execution_p_status_b78a87_idx'),
        ),
        migrations.AddIndex(
            model_name='executionpreparationresult',
            index=models.Index(fields=['order_plan'], name='execution_p_order_p_a8b0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='executionpreparationresult',
            index=models.Index(fields=['risk_check_result'], name='execution_p_risk_ch_69c0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='executionpreparationresult',
            index=models.Index(fields=['candidate_order_intent'], name='execution_p_candida_28f2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='executionpreparationresult',
            index=models.Index(fields=['trace_id'], name='execution_p_trace_i_302b95_idx'),
        ),
        migrations.AddIndex(
            model_name='preparedorderintent',
            index=models.Index(fields=['status', 'expires_at_utc'], name='execution_p_status_60a71e_idx'),
        ),
        migrations.AddIndex(
            model_name='preparedorderintent',
            index=models.Index(fields=['market_type', 'account_domain', 'symbol'], name='execution_p_market__969444_idx'),
        ),
        migrations.AddIndex(
            model_name='preparedorderintent',
            index=models.Index(fields=['source_order_plan'], name='execution_p_source__48e2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='preparedorderintent',
            index=models.Index(fields=['client_order_id'], name='execution_p_client__9b1438_idx'),
        ),
    ]
