# Generated by Django 5.2.15 on 2026-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_preparation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparedorderintent',
            name='status',
            field=models.CharField(choices=[('prepared', '待提交'), ('expired', '已过期'), ('consumed', '已进入执行'), ('submitted', '已提交'), ('submission_rejected', '提交被拒绝'), ('submission_unknown', '提交结果未知'), ('submission_blocked', '提交前阻断'), ('submission_failed', '提交前失败')], default='prepared', max_length=40, verbose_name='状态'),
        ),
    ]
