# Generated by Django 5.2.15 on 2026-06-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=191, unique=True, verbose_name='编排运行幂等键')),
                ('pipeline_code', models.CharField(max_length=80, verbose_name='流水线代码')),
                ('registry_version', models.CharField(max_length=80, verbose_name='Registry 版本')),
                ('registry_hash', models.CharField(max_length=80, verbose_name='Registry 指纹')),
                ('strategy_analysis_release_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='冻结策略版本包 ID')),
                ('strategy_analysis_release_hash', models.CharField(blank=True, max_length=80, verbose_name='冻结策略版本包指纹')),
                ('strategy_analysis_release_freeze_status', models.CharField(blank=True, max_length=40, verbose_name='策略版本冻结状态')),
                ('strategy_analysis_release_freeze_reason_code', models.CharField(blank=True, max_length=120, verbose_name='策略版本冻结原因')),
                ('run_config_snapshot_hash', models.CharField(blank=True, max_length=80, verbose_name='运行配置快照指纹')),
                ('scheduled_for_utc', models.DateTimeField(verbose_name='计划 UTC 时间')),
                ('cycle_kind', models.CharField(max_length=80, verbose_name='周期类型')),
                ('trigger_mode', models.CharField(choices=[('automatic', '自动'), ('manual_diagnostic', '人工诊断'), ('manual_recovery', '人工恢复')], max_length=40, verbose_name='触发模式')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('status', models.CharField(choices=[('created', '已创建'), ('running', '运行中'), ('waiting', '等待中'), ('completed', '已完成'), ('completed_no_action', '无动作完成'), ('blocked', '受控阻断'), ('unknown', '未知结束'), ('failed', '失败'), ('stale_interrupted', '过期中断')], max_length=40, verbose_name='运行状态')),
                ('final_outcome', models.CharField(blank=True, choices=[('', '未结束'), ('succeeded', '成功'), ('no_action', '无动作'), ('blocked', '阻断'), ('unknown', '未知'), ('failed', '失败'), ('stale_interrupted', '过期中断')], max_length=40, verbose_name='最终结果')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('current_step_code', models.CharField(blank=True, max_length=80, verbose_name='当前步骤')),
                ('last_completed_step_code', models.CharField(blank=True, max_length=80, verbose_name='最后完成步骤')),
                ('last_stopped_step_code', models.CharField(blank=True, max_length=80, verbose_name='停止步骤')),
                ('needs_manual_attention', models.BooleanField(default=False, verbose_name='是否需要人工关注')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('started_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='开始 UTC 时间')),
                ('waiting_since_utc', models.DateTimeField(blank=True, null=True, verbose_name='等待开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='完成 UTC 时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_at_utc'], name='orchestrati_status_02e5d1_idx'), models.Index(fields=['pipeline_code', 'scheduled_for_utc'], name='orchestrati_pipelin_a059be_idx'), models.Index(fields=['trace_id'], name='orchestrati_trace_i_4511cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('pipeline_code', 'scheduled_for_utc', 'cycle_kind', 'trigger_mode'), name='uniq_orchestration_run_schedule')],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationRunConfigSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_version', models.CharField(max_length=80, verbose_name='Registry 版本')),
                ('registry_hash', models.CharField(max_length=80, verbose_name='Registry 指纹')),
                ('strategy_analysis_release_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='冻结策略版本包 ID')),
                ('strategy_analysis_release_hash', models.CharField(blank=True, max_length=80, verbose_name='冻结策略版本包指纹')),
                ('adapter_versions', models.JSONField(default=dict, verbose_name='Adapter 版本')),
                ('result_mapping_versions', models.JSONField(default=dict, verbose_name='结果映射版本')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='运行配置快照')),
                ('snapshot_hash', models.CharField(max_length=80, verbose_name='快照指纹')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('orchestration_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshot', to='orchestration.orchestrationrun')),
            ],
        ),
        migrations.CreateModel(
            name='OrchestrationStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=80, verbose_name='步骤代码')),
                ('module_code', models.CharField(max_length=80, verbose_name='模块代码')),
                ('adapter_code', models.CharField(max_length=120, verbose_name='Adapter 代码')),
                ('adapter_version', models.CharField(max_length=80, verbose_name='Adapter 版本')),
                ('result_mapping_version', models.CharField(max_length=80, verbose_name='结果映射版本')),
                ('execution_sequence', models.PositiveIntegerField(verbose_name='执行序号')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('status', models.CharField(choices=[('created', '已创建'), ('running', '运行中'), ('waiting', '等待中'), ('succeeded', '成功'), ('no_action', '无动作'), ('blocked', '阻断'), ('unknown', '未知'), ('failed', '失败'), ('skipped', '跳过')], max_length=40, verbose_name='步骤状态')),
                ('normalized_status', models.CharField(blank=True, max_length=40, verbose_name='统一业务状态')),
                ('flow_action', models.CharField(blank=True, max_length=40, verbose_name='流程动作')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('reason_message', models.CharField(blank=True, max_length=500, verbose_name='原因说明')),
                ('raw_business_status', models.CharField(blank=True, max_length=80, verbose_name='原始业务状态')),
                ('raw_result_summary', models.JSONField(blank=True, default=dict, verbose_name='脱敏原始结果摘要')),
                ('raw_result_hash', models.CharField(blank=True, max_length=80, verbose_name='原始结果指纹')),
                ('primary_object_type', models.CharField(blank=True, max_length=120, verbose_name='主对象类型')),
                ('primary_object_id', models.CharField(blank=True, max_length=120, verbose_name='主对象 ID')),
                ('resume_token', models.CharField(blank=True, max_length=191, null=True, unique=True, verbose_name='恢复令牌')),
                ('resume_step_code', models.CharField(blank=True, max_length=80, verbose_name='恢复步骤')),
                ('waiting_object_type', models.CharField(blank=True, max_length=120, verbose_name='等待对象类型')),
                ('waiting_object_id', models.CharField(blank=True, max_length=120, verbose_name='等待对象 ID')),
                ('next_check_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='下次检查 UTC 时间')),
                ('needs_manual_attention', models.BooleanField(default=False, verbose_name='是否需要人工关注')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('started_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='开始 UTC 时间')),
                ('waiting_since_utc', models.DateTimeField(blank=True, null=True, verbose_name='等待开始 UTC 时间')),
                ('finished_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='完成 UTC 时间')),
                ('last_status_updated_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='最后状态更新时间')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('orchestration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='orchestration.orchestrationrun')),
            ],
        ),
        migrations.CreateModel(
            name='OrchestrationBusinessObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=80, verbose_name='步骤代码')),
                ('module_code', models.CharField(max_length=80, verbose_name='模块代码')),
                ('object_role', models.CharField(choices=[('primary', '主对象'), ('input', '输入对象'), ('output', '输出对象'), ('related', '相关对象'), ('audit', '审计对象')], max_length=40, verbose_name='对象角色')),
                ('object_type', models.CharField(max_length=120, verbose_name='对象类型')),
                ('object_id', models.CharField(max_length=120, verbose_name='对象 ID')),
                ('object_label', models.CharField(blank=True, max_length=200, verbose_name='对象标签')),
                ('ref_strategy', models.CharField(default='explicit_refs', max_length=40, verbose_name='引用策略')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('orchestration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_object_links', to='orchestration.orchestrationrun')),
                ('step_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_object_links', to='orchestration.orchestrationsteprun')),
            ],
        ),
        migrations.AddIndex(
            model_name='orchestrationsteprun',
            index=models.Index(fields=['orchestration_run', 'execution_sequence'], name='orchestrati_orchest_4f566b_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationsteprun',
            index=models.Index(fields=['status', 'updated_at_utc'], name='orchestrati_status_3cc35b_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationsteprun',
            index=models.Index(fields=['step_code', 'status'], name='orchestrati_step_co_0abd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationsteprun',
            index=models.Index(fields=['trace_id'], name='orchestrati_trace_i_6e504a_idx'),
        ),
        migrations.AddConstraint(
            model_name='orchestrationsteprun',
            constraint=models.UniqueConstraint(fields=('orchestration_run', 'step_code', 'execution_sequence'), name='uniq_orchestration_step_sequence'),
        ),
        migrations.AddIndex(
            model_name='orchestrationbusinessobjectlink',
            index=models.Index(fields=['orchestration_run', 'step_code'], name='orchestrati_orchest_01c353_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationbusinessobjectlink',
            index=models.Index(fields=['object_type', 'object_id'], name='orchestrati_object__11025f_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationbusinessobjectlink',
            index=models.Index(fields=['step_code', 'object_type'], name='orchestrati_step_co_918c59_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationbusinessobjectlink',
            index=models.Index(fields=['trace_id'], name='orchestrati_trace_i_d757ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='orchestrationbusinessobjectlink',
            constraint=models.UniqueConstraint(fields=('step_run', 'object_role', 'object_type', 'object_id'), name='uniq_orchestration_object_link'),
        ),
    ]
