# Generated by Django 5.2.15 on 2026-06-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fill_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfillsummary',
            name='filled_notional_usd',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='COIN-M 合约名义金额'),
        ),
        migrations.AddField(
            model_name='tradefill',
            name='contract_size',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True, verbose_name='合约面值'),
        ),
    ]
