# Generated by Django 5.2.15 on 2026-06-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=120, verbose_name='操作者 ID')),
                ('operation_type', models.CharField(max_length=120, verbose_name='操作类型')),
                ('target_object_type', models.CharField(max_length=120, verbose_name='目标对象类型')),
                ('target_object_id', models.CharField(blank=True, max_length=120, verbose_name='目标对象 ID')),
                ('before_state_summary', models.JSONField(blank=True, default=dict, verbose_name='修改前状态摘要')),
                ('after_state_summary', models.JSONField(blank=True, default=dict, verbose_name='修改后状态摘要')),
                ('reason', models.CharField(max_length=500, verbose_name='操作原因')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='操作证据')),
                ('result', models.CharField(max_length=80, verbose_name='操作结果')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
            ],
            options={
                'verbose_name': '审计记录',
                'verbose_name_plural': '审计记录',
                'indexes': [models.Index(fields=['operator_id', 'created_at_utc'], name='audit_audit_operato_8d8b64_idx'), models.Index(fields=['target_object_type', 'target_object_id'], name='audit_audit_target__39e772_idx'), models.Index(fields=['trace_id'], name='audit_audit_trace_i_f53800_idx')],
            },
        ),
    ]
