# Generated by Django 5.2.15 on 2026-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('price_type', models.CharField(choices=[('mark_price', '标记价格')], default='mark_price', max_length=40, verbose_name='价格类型')),
                ('mark_price', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='标记价格')),
                ('price_unit', models.CharField(max_length=40, verbose_name='价格单位')),
                ('source', models.CharField(default='binance_rest', max_length=80, verbose_name='来源')),
                ('source_operation', models.CharField(default='get_mark_price', max_length=80, verbose_name='来源操作')),
                ('source_update_time_utc', models.DateTimeField(verbose_name='Binance 价格更新时间')),
                ('requested_at_utc', models.DateTimeField(verbose_name='请求开始 UTC 时间')),
                ('received_at_utc', models.DateTimeField(verbose_name='收到响应 UTC 时间')),
                ('as_of_utc', models.DateTimeField(verbose_name='价格事实 UTC 时间')),
                ('expires_at_utc', models.DateTimeField(verbose_name='过期 UTC 时间')),
                ('gateway_latency_ms', models.IntegerField(default=0, verbose_name='Gateway 延迟毫秒')),
                ('gateway_attempt_count', models.IntegerField(default=0, verbose_name='Gateway 尝试次数')),
                ('price_snapshot_hash', models.CharField(max_length=80, verbose_name='价格快照 hash')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='脱敏原始载荷')),
                ('gateway_call_summary', models.JSONField(blank=True, default=dict, verbose_name='Gateway 调用摘要')),
                ('trace_id', models.CharField(max_length=80, verbose_name='追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
            ],
            options={
                'indexes': [models.Index(fields=['market_type', 'account_domain', 'symbol'], name='price_snaps_market__69f947_idx'), models.Index(fields=['expires_at_utc'], name='price_snaps_expires_b381cd_idx'), models.Index(fields=['trace_id'], name='price_snaps_trace_i_941092_idx'), models.Index(fields=['price_snapshot_hash'], name='price_snaps_price_s_64c413_idx')],
            },
        ),
    ]
