# Generated by Django 5.2.15 on 2026-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedorderintent',
            name='status',
            field=models.CharField(choices=[('approved', '已审批通过'), ('expired', '已过期'), ('canceled', '已取消'), ('consumed', '已进入执行准备'), ('execution_prepared', '执行准备完成'), ('preparation_blocked', '执行准备阻断'), ('preparation_failed', '执行准备失败'), ('preparation_expired', '执行准备过期')], default='approved', max_length=40, verbose_name='状态'),
        ),
    ]
