# Generated by Django 5.2.15 on 2026-06-24 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('binance_account_sync', '0001_initial'),
        ('price_snapshot', '0001_initial'),
        ('strategy_analysis', '0010_decisionpolicydefinition_decisionsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_request_key', models.CharField(max_length=191, unique=True, verbose_name='业务幂等键')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('position_mode', models.CharField(max_length=40, verbose_name='持仓模式')),
                ('target_position_ratio', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='目标总仓位比例')),
                ('current_equity', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='当前账户权益')),
                ('current_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='当前有符号仓位')),
                ('raw_target_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='原始目标有符号仓位')),
                ('target_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='规范化目标有符号仓位')),
                ('delta_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='有符号调仓差额')),
                ('mark_price', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='绑定标记价格')),
                ('target_notional', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='目标名义价值')),
                ('normalized_order_notional', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='规范化订单名义价值')),
                ('min_rebalance_notional', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='最小调仓名义阈值')),
                ('max_target_notional_to_equity_ratio', models.DecimalField(decimal_places=18, max_digits=20, verbose_name='目标名义相对权益上限比例')),
                ('status', models.CharField(choices=[('created', '已创建'), ('no_order_required', '无需调仓'), ('blocked', '已阻断'), ('failed', '失败')], max_length=40, verbose_name='状态')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('allows_downstream', models.BooleanField(default=False, verbose_name='是否允许进入风控')),
                ('config_snapshot', models.JSONField(default=dict, verbose_name='配置快照')),
                ('calculation_evidence', models.JSONField(default=dict, verbose_name='计算证据')),
                ('order_plan_hash', models.CharField(max_length=80, verbose_name='订单计划指纹')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('account_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='binance_account_sync.binanceaccountsnapshot')),
                ('balance_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='binance_account_sync.binancebalancesnapshot')),
                ('binance_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='binance_account_sync.binancesyncrun')),
                ('decision_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='strategy_analysis.decisionsnapshot')),
                ('position_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='binance_account_sync.binancepositionsnapshot')),
                ('price_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='price_snapshot.pricesnapshot')),
                ('symbol_rule_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='binance_account_sync.binancesymbolrulesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlanActiveLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(default='binance', max_length=40, verbose_name='交易所')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('status', models.CharField(choices=[('active', '保护中'), ('released', '已释放'), ('failed', '收尾异常')], max_length=40, verbose_name='锁状态')),
                ('acquired_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='取得 UTC 时间')),
                ('released_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='释放 UTC 时间')),
                ('failed_at_utc', models.DateTimeField(blank=True, null=True, verbose_name='异常 UTC 时间')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='当前原因代码')),
                ('version', models.PositiveBigIntegerField(default=1, verbose_name='状态版本')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('updated_at_utc', models.DateTimeField(auto_now=True, verbose_name='更新 UTC 时间')),
                ('current_order_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_active_locks', to='order_plan.orderplan')),
            ],
        ),
        migrations.AddField(
            model_name='orderplan',
            name='active_lock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_plans', to='order_plan.orderplanactivelock'),
        ),
        migrations.CreateModel(
            name='OrderPlanActiveLockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=191, unique=True, verbose_name='锁事件幂等键')),
                ('event_type', models.CharField(max_length=80, verbose_name='事件类型')),
                ('from_status', models.CharField(blank=True, max_length=40, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=40, verbose_name='新状态')),
                ('reason_code', models.CharField(max_length=120, verbose_name='原因代码')),
                ('evidence', models.JSONField(default=dict, verbose_name='收尾或取得证据')),
                ('operator_id', models.CharField(blank=True, max_length=120, verbose_name='人工操作人')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('trigger_source', models.CharField(max_length=80, verbose_name='触发来源')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('active_lock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='order_plan.orderplanactivelock')),
                ('order_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_lock_events', to='order_plan.orderplan')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateOrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_role', models.CharField(choices=[('primary', '主候选意图'), ('fallback_reduce_only', '只减仓后备意图')], max_length=40, verbose_name='候选意图角色')),
                ('symbol', models.CharField(max_length=40, verbose_name='交易品种')),
                ('market_type', models.CharField(max_length=40, verbose_name='市场类型')),
                ('account_domain', models.CharField(max_length=120, verbose_name='账户域')),
                ('position_mode', models.CharField(max_length=40, verbose_name='持仓模式')),
                ('order_type', models.CharField(default='MARKET', max_length=40, verbose_name='订单类型')),
                ('plan_type', models.CharField(max_length=80, verbose_name='仓位转换类型')),
                ('side', models.CharField(max_length=10, verbose_name='订单方向')),
                ('position_side', models.CharField(default='BOTH', max_length=20, verbose_name='持仓方向')),
                ('exchange_reduce_only', models.BooleanField(default=False, verbose_name='交易所 reduceOnly')),
                ('requested_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='请求数量')),
                ('requested_notional', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='请求名义价值')),
                ('requested_size_unit', models.CharField(max_length=40, verbose_name='请求数量单位')),
                ('reference_mark_price', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='参考标记价格')),
                ('current_position_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='当前有符号仓位')),
                ('target_position_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='目标有符号仓位')),
                ('delta_signed_size', models.DecimalField(decimal_places=18, max_digits=38, verbose_name='有符号调仓差额')),
                ('closing_size', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='平旧仓数量')),
                ('opening_size', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='开新仓数量')),
                ('residual_position_size', models.DecimalField(decimal_places=18, default=0, max_digits=38, verbose_name='不可交易残余仓位')),
                ('order_components', models.JSONField(default=list, verbose_name='订单风险组件')),
                ('status', models.CharField(choices=[('pending_risk_check', '等待风控'), ('approved', '已通过风控'), ('denied', '风控拒绝'), ('blocked', '风控阻断'), ('canceled', '已取消')], default='pending_risk_check', max_length=40, verbose_name='状态')),
                ('reason_code', models.CharField(blank=True, max_length=120, verbose_name='原因代码')),
                ('evidence', models.JSONField(default=dict, verbose_name='证据')),
                ('intent_hash', models.CharField(max_length=80, verbose_name='候选意图指纹')),
                ('trace_id', models.CharField(max_length=80, verbose_name='技术追踪 ID')),
                ('created_at_utc', models.DateTimeField(auto_now_add=True, verbose_name='创建 UTC 时间')),
                ('binance_sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_order_intents', to='binance_account_sync.binancesyncrun')),
                ('current_position_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_order_intents', to='binance_account_sync.binancepositionsnapshot')),
                ('price_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_order_intents', to='price_snapshot.pricesnapshot')),
                ('symbol_rule_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_order_intents', to='binance_account_sync.binancesymbolrulesnapshot')),
                ('order_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_intents', to='order_plan.orderplan')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at_utc'], name='order_plan__status_9e857b_idx'), models.Index(fields=['market_type', 'account_domain', 'symbol'], name='order_plan__market__62e6b0_idx'), models.Index(fields=['intent_hash'], name='order_plan__intent__45ae23_idx'), models.Index(fields=['trace_id'], name='order_plan__trace_i_ef06ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_plan', 'intent_role'), name='uniq_candidate_intent_role_per_plan')],
            },
        ),
        migrations.AddIndex(
            model_name='orderplanactivelock',
            index=models.Index(fields=['status', 'updated_at_utc'], name='order_plan__status_0f4f61_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplanactivelock',
            index=models.Index(fields=['current_order_plan'], name='order_plan__current_68d80f_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderplanactivelock',
            constraint=models.UniqueConstraint(fields=('exchange', 'market_type', 'account_domain', 'symbol'), name='uniq_order_plan_active_lock_identity'),
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['market_type', 'account_domain', 'symbol', 'status'], name='order_plan__market__cf1983_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['decision_snapshot'], name='order_plan__decisio_d9d5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['binance_sync_run'], name='order_plan__binance_d69bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['price_snapshot'], name='order_plan__price_s_c79bab_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['trace_id'], name='order_plan__trace_i_2eb985_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplan',
            index=models.Index(fields=['order_plan_hash'], name='order_plan__order_p_701d77_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplanactivelockevent',
            index=models.Index(fields=['active_lock', 'created_at_utc'], name='order_plan__active__63e1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplanactivelockevent',
            index=models.Index(fields=['order_plan'], name='order_plan__order_p_59bd56_idx'),
        ),
        migrations.AddIndex(
            model_name='orderplanactivelockevent',
            index=models.Index(fields=['trace_id'], name='order_plan__trace_i_1609d4_idx'),
        ),
    ]
