# Generated by Django 5.2.15 on 2026-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplan',
            name='target_position_ratio',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True, verbose_name='目标总仓位比例'),
        ),
    ]
