# Generated by Django 5.2.15 on 2026-06-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_plan', '0002_alter_orderplan_target_position_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplan',
            name='status',
            field=models.CharField(choices=[('created', '已创建'), ('no_order_required', '无需调仓'), ('blocked', '已阻断'), ('failed', '失败'), ('preparation_blocked', '执行准备阻断'), ('preparation_failed', '执行准备失败'), ('preparation_expired', '执行准备过期')], max_length=40, verbose_name='状态'),
        ),
    ]
